MultiLanguageNpcData['cn'][64971] = {name = "扎尼提克穿刺者", subname = nil}
MultiLanguageNpcData['cn'][64973] = {name = "扎尼提克操纵者", subname = nil}
MultiLanguageNpcData['cn'][64977] = {name = "玛瑙云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][64979] = {name = "巢卫维克阿兹", subname = nil}
MultiLanguageNpcData['cn'][64982] = {name = "扎尼提克珀牙蝎", subname = nil}
MultiLanguageNpcData['cn'][65008] = {name = "火金派武僧", subname = nil}
MultiLanguageNpcData['cn'][65035] = {name = "夏百合", subname = nil}
MultiLanguageNpcData['cn'][65037] = {name = "塑树者苏叶", subname = nil}
MultiLanguageNpcData['cn'][65039] = {name = "恩·泥犁", subname = nil}
MultiLanguageNpcData['cn'][65042] = {name = "安详的舜", subname = nil}
MultiLanguageNpcData['cn'][65043] = {name = "橡掌长老", subname = "专业技能训练师"}
MultiLanguageNpcData['cn'][65044] = {name = "甘·暗桶", subname = nil}
MultiLanguageNpcData['cn'][65045] = {name = "高·长车", subname = nil}
MultiLanguageNpcData['cn'][65046] = {name = "老马良", subname = "旅店老板"}
MultiLanguageNpcData['cn'][65047] = {name = "易风", subname = "食物商"}
MultiLanguageNpcData['cn'][65049] = {name = "阿二", subname = "饮料商"}
MultiLanguageNpcData['cn'][65050] = {name = "萨安", subname = "食物商"}
MultiLanguageNpcData['cn'][65052] = {name = "老施", subname = "饮料商"}
MultiLanguageNpcData['cn'][65053] = {name = "白花", subname = "女招待"}
MultiLanguageNpcData['cn'][65055] = {name = "独眼韩诗", subname = nil}
MultiLanguageNpcData['cn'][65056] = {name = "骗子长须", subname = nil}
MultiLanguageNpcData['cn'][65057] = {name = "范·钝犁", subname = nil}
MultiLanguageNpcData['cn'][65058] = {name = "黑色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65059] = {name = "京·酒胆", subname = nil}
MultiLanguageNpcData['cn'][65060] = {name = "蓝色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65061] = {name = "棕色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65062] = {name = "铁腹邵离", subname = "饮酒大赛冠军"}
MultiLanguageNpcData['cn'][65063] = {name = "紫色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65064] = {name = "沉思的齐罗", subname = nil}
MultiLanguageNpcData['cn'][65065] = {name = "红色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65067] = {name = "峭壁大师缇拉", subname = nil}
MultiLanguageNpcData['cn'][65068] = {name = "老白鼻", subname = "龙龟饲养员"}
MultiLanguageNpcData['cn'][65070] = {name = "高凯·利锄", subname = nil}
MultiLanguageNpcData['cn'][65071] = {name = "巨型绿色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65073] = {name = "奈拉·水园", subname = nil}
MultiLanguageNpcData['cn'][65074] = {name = "巨型蓝色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65075] = {name = "紫兰", subname = nil}
MultiLanguageNpcData['cn'][65076] = {name = "巨型棕色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65077] = {name = "园丁艾玛丽", subname = nil}
MultiLanguageNpcData['cn'][65078] = {name = "巨型紫色龙龟", subname = nil}
MultiLanguageNpcData['cn'][65080] = {name = "气功大师林", subname = nil}
MultiLanguageNpcData['cn'][65084] = {name = "赤红蝴蝶", subname = nil}
MultiLanguageNpcData['cn'][65085] = {name = "槿", subname = nil}
MultiLanguageNpcData['cn'][65086] = {name = "妲娜", subname = nil}
MultiLanguageNpcData['cn'][65087] = {name = "商人老冯", subname = "杂货商"}
MultiLanguageNpcData['cn'][65088] = {name = "园丁老沈", subname = nil}
MultiLanguageNpcData['cn'][65089] = {name = "老杨", subname = nil}
MultiLanguageNpcData['cn'][65092] = {name = "冶炼大师灰掌", subname = "采矿训练师"}
MultiLanguageNpcData['cn'][65093] = {name = "女预言师翁舞", subname = nil}
MultiLanguageNpcData['cn'][65094] = {name = "五晨司祭", subname = nil}
MultiLanguageNpcData['cn'][65098] = {name = "塑玉者麦逸", subname = "珠宝加工训练师"}
MultiLanguageNpcData['cn'][65102] = {name = "大风", subname = "上古风灵"}
MultiLanguageNpcData['cn'][65104] = {name = "无垢", subname = "上古土灵"}
MultiLanguageNpcData['cn'][65105] = {name = "涓流", subname = "上古水灵"}
MultiLanguageNpcData['cn'][65107] = {name = "燧焰", subname = "上古火灵"}
MultiLanguageNpcData['cn'][65111] = {name = "蟠龙脊防御者", subname = nil}
MultiLanguageNpcData['cn'][65114] = {name = "“大锤”铁伦", subname = "锻造训练师"}
MultiLanguageNpcData['cn'][65118] = {name = "针背箭猪", subname = nil}
MultiLanguageNpcData['cn'][65121] = {name = "亮皮带", subname = "制皮训练师"}
MultiLanguageNpcData['cn'][65146] = {name = "周泽客", subname = nil}
MultiLanguageNpcData['cn'][65147] = {name = "阿钻", subname = "周泽客的宠物"}
MultiLanguageNpcData['cn'][65148] = {name = "史奇奥", subname = nil}
MultiLanguageNpcData['cn'][65149] = {name = "卡拉克西瓦·洛尔", subname = nil}
MultiLanguageNpcData['cn'][65164] = {name = "洛克诺·血拳", subname = "荣誉军需官"}
MultiLanguageNpcData['cn'][65165] = {name = "桃丽丝·奇尔顿妮斯", subname = "征服军需官"}
MultiLanguageNpcData['cn'][65166] = {name = "海登·克里斯托芬", subname = "荣誉军需官"}
MultiLanguageNpcData['cn'][65167] = {name = "鲁坎·马洛里", subname = "征服军需官"}
MultiLanguageNpcData['cn'][65168] = {name = "简易破门炸弹", subname = nil}
MultiLanguageNpcData['cn'][65169] = {name = "青玉巨神像", subname = nil}
MultiLanguageNpcData['cn'][65170] = {name = "青玉战士", subname = nil}
MultiLanguageNpcData['cn'][65186] = {name = "下毒者克尔兹特", subname = "炼金训练师"}
MultiLanguageNpcData['cn'][65191] = {name = "猫鼬", subname = nil}
MultiLanguageNpcData['cn'][65192] = {name = "猫鼬幼崽", subname = nil}
MultiLanguageNpcData['cn'][65204] = {name = "兴奋的萤火虫", subname = nil}
MultiLanguageNpcData['cn'][65205] = {name = "镀金飞蛾", subname = nil}
MultiLanguageNpcData['cn'][65206] = {name = "金色麝猫", subname = nil}
MultiLanguageNpcData['cn'][65207] = {name = "金色麝猫幼崽", subname = nil}
MultiLanguageNpcData['cn'][65209] = {name = "欢跃水黾", subname = nil}
MultiLanguageNpcData['cn'][65211] = {name = "黄腹牛蛙", subname = nil}
MultiLanguageNpcData['cn'][65223] = {name = "亡首蟑螂", subname = nil}
MultiLanguageNpcData['cn'][65227] = {name = "Mogu Runes (Pitch Forward 120) DNT", subname = nil}
MultiLanguageNpcData['cn'][65228] = {name = "Mogu Runes (Pitch Forward 180) DNT", subname = nil}
MultiLanguageNpcData['cn'][65229] = {name = "凯帕拉克", subname = nil}
MultiLanguageNpcData['cn'][65231] = {name = "凯帕爬行者", subname = nil}
MultiLanguageNpcData['cn'][65247] = {name = "Player Clone (TEMP)", subname = nil}
MultiLanguageNpcData['cn'][65248] = {name = "凯迪·叁咏", subname = nil}
MultiLanguageNpcData['cn'][65251] = {name = "徘徊之惧", subname = nil}
MultiLanguageNpcData['cn'][65253] = {name = "切割者里卡尔", subname = nil}
MultiLanguageNpcData['cn'][65257] = {name = "逸出的煞魔", subname = nil}
MultiLanguageNpcData['cn'][65273] = {name = "扎尼提克穿刺者", subname = nil}
MultiLanguageNpcData['cn'][65274] = {name = "扎尼提克操纵者", subname = nil}
MultiLanguageNpcData['cn'][65283] = {name = "坠落残片", subname = nil}
MultiLanguageNpcData['cn'][65287] = {name = "Survival Ring Blades Controller", subname = nil}
MultiLanguageNpcData['cn'][65288] = {name = "影踪派训练师", subname = nil}
MultiLanguageNpcData['cn'][65293] = {name = "永恒之能", subname = nil}
MultiLanguageNpcData['cn'][65297] = {name = "隐形的潜伏者", subname = nil}
MultiLanguageNpcData['cn'][65310] = {name = "芜菁沙袋", subname = nil}
MultiLanguageNpcData['cn'][65325] = {name = "可踢的土拨鼠", subname = nil}
MultiLanguageNpcData['cn'][65327] = {name = "神射手兰", subname = nil}
MultiLanguageNpcData['cn'][65332] = {name = "作战翔龙", subname = nil}
MultiLanguageNpcData['cn'][65337] = {name = "蟠龙脊防御者", subname = nil}
MultiLanguageNpcData['cn'][65343] = {name = "白骨蜘蛛", subname = nil}
MultiLanguageNpcData['cn'][65348] = {name = "旋风之刃", subname = nil}
MultiLanguageNpcData['cn'][65357] = {name = "一个神秘的声音", subname = nil}
MultiLanguageNpcData['cn'][65363] = {name = "Kil'ruk Awaken Bunny", subname = nil}
MultiLanguageNpcData['cn'][65371] = {name = "掠风者克尔鲁克", subname = nil}
MultiLanguageNpcData['cn'][65374] = {name = "闪电吐息", subname = nil}
MultiLanguageNpcData['cn'][65377] = {name = "青玉战士", subname = nil}
MultiLanguageNpcData['cn'][65387] = {name = "祥和图腾", subname = nil}
MultiLanguageNpcData['cn'][65395] = {name = "卡拉克西瓦·伊克", subname = nil}
MultiLanguageNpcData['cn'][65396] = {name = "卡拉克西瓦·库尔", subname = nil}
MultiLanguageNpcData['cn'][65397] = {name = "卡拉克西瓦·科里克", subname = nil}
MultiLanguageNpcData['cn'][65398] = {name = "卡拉克西瓦·瑟拉", subname = nil}
MultiLanguageNpcData['cn'][65400] = {name = "科里克提克滑翔者", subname = nil}
MultiLanguageNpcData['cn'][65401] = {name = "科里克提克滑翔者", subname = nil}
MultiLanguageNpcData['cn'][65402] = {name = "格尔桑捷刃兵", subname = nil}
MultiLanguageNpcData['cn'][65409] = {name = "金·热桶的美酒", subname = nil}
MultiLanguageNpcData['cn'][65422] = {name = "无伤者玛里克", subname = nil}
MultiLanguageNpcData['cn'][65423] = {name = "迷失的灵魂", subname = nil}
MultiLanguageNpcData['cn'][65428] = {name = "训练有素的阿曼尼猛龙", subname = nil}
MultiLanguageNpcData['cn'][65429] = {name = "声波场", subname = nil}
MultiLanguageNpcData['cn'][65432] = {name = "凯帕琥珀粉碎者", subname = nil}
MultiLanguageNpcData['cn'][65434] = {name = "General Purpose Bunny ZTO", subname = nil}
MultiLanguageNpcData['cn'][65435] = {name = "恐惧碎珀者", subname = nil}
MultiLanguageNpcData['cn'][65440] = {name = "Fire Beam Bunny", subname = nil}
MultiLanguageNpcData['cn'][65443] = {name = "炸弹目标", subname = nil}
MultiLanguageNpcData['cn'][65445] = {name = "螳螂妖", subname = nil}
MultiLanguageNpcData['cn'][65446] = {name = "地精船长", subname = nil}
MultiLanguageNpcData['cn'][65447] = {name = "地精水兵", subname = nil}
MultiLanguageNpcData['cn'][65449] = {name = "地精船员", subname = nil}
MultiLanguageNpcData['cn'][65451] = {name = "残阳关", subname = nil}
MultiLanguageNpcData['cn'][65455] = {name = "科里克提克飞翼护卫", subname = nil}
MultiLanguageNpcData['cn'][65456] = {name = "琥珀撼地者", subname = nil}
MultiLanguageNpcData['cn'][65467] = {name = "兴奋的围观者", subname = nil}
MultiLanguageNpcData['cn'][65468] = {name = "土水派武僧", subname = nil}
MultiLanguageNpcData['cn'][65469] = {name = "有志气的徒弟", subname = nil}
MultiLanguageNpcData['cn'][65470] = {name = "火金派弟子", subname = nil}
MultiLanguageNpcData['cn'][65471] = {name = "土水派弟子", subname = nil}
MultiLanguageNpcData['cn'][65472] = {name = "武松村民", subname = nil}
MultiLanguageNpcData['cn'][65473] = {name = "大箩耕农", subname = nil}
MultiLanguageNpcData['cn'][65476] = {name = "Balloon Air Spirit Bunny", subname = nil}
MultiLanguageNpcData['cn'][65477] = {name = "Balloon Fire Spirit Bunny", subname = nil}
MultiLanguageNpcData['cn'][65478] = {name = "副官赛图克", subname = "夏柯希尔之手"}
MultiLanguageNpcData['cn'][65488] = {name = "惊怖精华", subname = nil}
MultiLanguageNpcData['cn'][65490] = {name = "惊骇精华", subname = nil}
MultiLanguageNpcData['cn'][65493] = {name = "涓流", subname = "上古水灵"}
MultiLanguageNpcData['cn'][65495] = {name = "影踪派神射手", subname = nil}
MultiLanguageNpcData['cn'][65512] = {name = "Warlord Gurthan Controller", subname = nil}
MultiLanguageNpcData['cn'][65513] = {name = "恐惧巨兽", subname = nil}
MultiLanguageNpcData['cn'][65514] = {name = "伊桑·那提斯", subname = "精锐征服军需官"}
MultiLanguageNpcData['cn'][65515] = {name = "阿肯·死亡统御", subname = "精锐征服军需官"}
MultiLanguageNpcData['cn'][65528] = {name = "楠·雷脚", subname = "旅店老板"}
MultiLanguageNpcData['cn'][65529] = {name = "折钢者杜术", subname = "铁匠"}
MultiLanguageNpcData['cn'][65530] = {name = "李海", subname = nil}
MultiLanguageNpcData['cn'][65531] = {name = "齐长老", subname = nil}
MultiLanguageNpcData['cn'][65532] = {name = "朱长老", subname = "卓金村长老"}
MultiLanguageNpcData['cn'][65533] = {name = "侯长老", subname = nil}
MultiLanguageNpcData['cn'][65534] = {name = "科亚", subname = nil}
MultiLanguageNpcData['cn'][65535] = {name = "刘哲", subname = "旅店老板"}
MultiLanguageNpcData['cn'][65536] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][65537] = {name = "蟠龙脊炮手", subname = nil}
MultiLanguageNpcData['cn'][65545] = {name = "火金派武僧", subname = nil}
MultiLanguageNpcData['cn'][65550] = {name = "土水派武僧", subname = nil}
MultiLanguageNpcData['cn'][65555] = {name = "Bonfire Teleport Stalker", subname = nil}
MultiLanguageNpcData['cn'][65558] = {name = "火金武僧", subname = nil}
MultiLanguageNpcData['cn'][65559] = {name = "炤壬的幻象", subname = "玛瑙蟠螭"}
MultiLanguageNpcData['cn'][65560] = {name = "大风的幻象", subname = "上古风灵"}
MultiLanguageNpcData['cn'][65561] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][65594] = {name = "提兹·电容", subname = "探险者协会"}
MultiLanguageNpcData['cn'][65596] = {name = "小罐头", subname = nil}
MultiLanguageNpcData['cn'][65598] = {name = "卡桑利符文守卫", subname = nil}
MultiLanguageNpcData['cn'][65600] = {name = "雕龙人", subname = nil}
MultiLanguageNpcData['cn'][65601] = {name = "雕龙人", subname = nil}
MultiLanguageNpcData['cn'][65622] = {name = "悲泣寡妇蛛", subname = nil}
MultiLanguageNpcData['cn'][65626] = {name = "都阳暴徒", subname = nil}
MultiLanguageNpcData['cn'][65627] = {name = "沙背护卫兽", subname = nil}
MultiLanguageNpcData['cn'][65629] = {name = "高地渡鸦", subname = nil}
MultiLanguageNpcData['cn'][65630] = {name = "雷电之王", subname = nil}
MultiLanguageNpcData['cn'][65632] = {name = "伊克提克恐爪蝎", subname = nil}
MultiLanguageNpcData['cn'][65638] = {name = "科夏奴监", subname = nil}
MultiLanguageNpcData['cn'][65646] = {name = "伊克提克塑恐者", subname = nil}
MultiLanguageNpcData['cn'][65648] = {name = "老马当劳", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][65651] = {name = "林塞", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][65655] = {name = "埃里克·戴维森", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][65656] = {name = "比尔·巴克勒", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][65688] = {name = "登山者", subname = nil}
MultiLanguageNpcData['cn'][65689] = {name = "登山绳索", subname = nil}
MultiLanguageNpcData['cn'][65711] = {name = "迅足虫", subname = nil}
MultiLanguageNpcData['cn'][65725] = {name = "云气", subname = nil}
MultiLanguageNpcData['cn'][65737] = {name = "货车", subname = nil}
MultiLanguageNpcData['cn'][65742] = {name = "逃脱的部落船员", subname = nil}
MultiLanguageNpcData['cn'][65743] = {name = "General Purpose Bunny (Gigantic AOI) (DLA)", subname = nil}
MultiLanguageNpcData['cn'][65744] = {name = "军军·滨水", subname = nil}
MultiLanguageNpcData['cn'][65745] = {name = "杜宇·滨水", subname = nil}
MultiLanguageNpcData['cn'][65746] = {name = "腾飞·滨水", subname = nil}
MultiLanguageNpcData['cn'][65747] = {name = "焰灵·滨水", subname = nil}
MultiLanguageNpcData['cn'][65748] = {name = "德明大叔", subname = nil}
MultiLanguageNpcData['cn'][65753] = {name = "Totally Generic Bunny - GIGANTIC (JSB)", subname = nil}
MultiLanguageNpcData['cn'][65758] = {name = "XE-321爆破机器人", subname = nil}
MultiLanguageNpcData['cn'][65763] = {name = "奥苏尔投树车", subname = nil}
MultiLanguageNpcData['cn'][65764] = {name = "奥苏尔入侵者", subname = nil}
MultiLanguageNpcData['cn'][65766] = {name = "老陈", subname = nil}
MultiLanguageNpcData['cn'][65767] = {name = "卡拉克西瓦·伊克", subname = nil}
MultiLanguageNpcData['cn'][65768] = {name = "风筝", subname = nil}
MultiLanguageNpcData['cn'][65771] = {name = "林·默拳", subname = nil}
MultiLanguageNpcData['cn'][65780] = {name = "贡达", subname = nil}
MultiLanguageNpcData['cn'][65781] = {name = "孙娜·默拳", subname = nil}
MultiLanguageNpcData['cn'][65782] = {name = "班·熊心", subname = nil}
MultiLanguageNpcData['cn'][65790] = {name = "筛泥蟹", subname = nil}
MultiLanguageNpcData['cn'][65803] = {name = "蓝晶矿石", subname = nil}
MultiLanguageNpcData['cn'][65838] = {name = "死亡的长毛绵羊", subname = nil}
MultiLanguageNpcData['cn'][65840] = {name = "铁腕飞行员", subname = nil}
MultiLanguageNpcData['cn'][65841] = {name = "铁腕列兵", subname = nil}
MultiLanguageNpcData['cn'][65842] = {name = "铁腕医护兵", subname = nil}
MultiLanguageNpcData['cn'][65843] = {name = "铁腕旋翼机", subname = nil}
MultiLanguageNpcData['cn'][65852] = {name = "昆莱山传送门", subname = nil}
MultiLanguageNpcData['cn'][65855] = {name = "米师", subname = "游学者周卓的伙伴"}
MultiLanguageNpcData['cn'][65857] = {name = "埋藏的头颅", subname = nil}
MultiLanguageNpcData['cn'][65860] = {name = "魔古灯柱", subname = nil}
MultiLanguageNpcData['cn'][65866] = {name = "金莲防御者", subname = nil}
MultiLanguageNpcData['cn'][65870] = {name = "梅·黑眉", subname = nil}
MultiLanguageNpcData['cn'][65874] = {name = "林·黒眉", subname = nil}
MultiLanguageNpcData['cn'][65877] = {name = "韩·繁花", subname = "草药学训练师"}
MultiLanguageNpcData['cn'][65880] = {name = "莫格斯·凶斧", subname = nil}
MultiLanguageNpcData['cn'][65881] = {name = "杰克逊·希尔瓦下士", subname = nil}
MultiLanguageNpcData['cn'][65882] = {name = "首席技师克格斯温", subname = nil}
MultiLanguageNpcData['cn'][65883] = {name = "陀螺技师拉文德普", subname = nil}
MultiLanguageNpcData['cn'][65884] = {name = "Stew Bunny", subname = nil}
MultiLanguageNpcData['cn'][65885] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][65886] = {name = "死亡的凯帕琥珀粉碎者", subname = nil}
MultiLanguageNpcData['cn'][65887] = {name = "死亡的泥鳞蜥蜴人", subname = nil}
MultiLanguageNpcData['cn'][65888] = {name = "Mogu Cannon Bunny", subname = nil}
MultiLanguageNpcData['cn'][65889] = {name = "苏石", subname = nil}
MultiLanguageNpcData['cn'][65890] = {name = "茂林·滨水", subname = nil}
MultiLanguageNpcData['cn'][65894] = {name = "宝宝", subname = nil}
MultiLanguageNpcData['cn'][65895] = {name = "砮皂", subname = "玄牛"}
MultiLanguageNpcData['cn'][65896] = {name = "卓金村民", subname = nil}
MultiLanguageNpcData['cn'][65897] = {name = "卓金村民", subname = nil}
MultiLanguageNpcData['cn'][65898] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][65899] = {name = "吉斯坦大师", subname = nil}
MultiLanguageNpcData['cn'][65902] = {name = "雪怒", subname = nil}
MultiLanguageNpcData['cn'][65903] = {name = "迷你魔法炸弹", subname = nil}
MultiLanguageNpcData['cn'][65904] = {name = "玉珑", subname = "青龙"}
MultiLanguageNpcData['cn'][65905] = {name = "铁腕中尉", subname = nil}
MultiLanguageNpcData['cn'][65906] = {name = "铁腕工人", subname = nil}
MultiLanguageNpcData['cn'][65915] = {name = "铁腕工人", subname = nil}
MultiLanguageNpcData['cn'][65918] = {name = "遭虫害的谜之种", subname = nil}
MultiLanguageNpcData['cn'][65925] = {name = "野生谜之种", subname = nil}
MultiLanguageNpcData['cn'][65961] = {name = "锦绣谷大门", subname = nil}
MultiLanguageNpcData['cn'][65974] = {name = "熊猫人志愿者", subname = nil}
MultiLanguageNpcData['cn'][65976] = {name = "调酒师拓莫若", subname = "旅店老板"}
MultiLanguageNpcData['cn'][65989] = {name = "魔法鳞茎", subname = nil}
MultiLanguageNpcData['cn'][65996] = {name = "纠缠之骇", subname = nil}
MultiLanguageNpcData['cn'][65998] = {name = "商人金宝", subname = nil}
MultiLanguageNpcData['cn'][65999] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66000] = {name = "铁腕王牌飞行员", subname = nil}
MultiLanguageNpcData['cn'][66016] = {name = "食肉草", subname = nil}
MultiLanguageNpcData['cn'][66022] = {name = "乌龟大师吴玳", subname = "龙龟饲养员"}
MultiLanguageNpcData['cn'][66036] = {name = "螳螂妖飞行者", subname = nil}
MultiLanguageNpcData['cn'][66052] = {name = "多伦上尉", subname = nil}
MultiLanguageNpcData['cn'][66053] = {name = "莱文·晨刃", subname = nil}
MultiLanguageNpcData['cn'][66055] = {name = "奎·秋光", subname = nil}
MultiLanguageNpcData['cn'][66056] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][66057] = {name = "鲁克·石趾", subname = nil}
MultiLanguageNpcData['cn'][66058] = {name = "和谐者智先生", subname = "金莲护法"}
MultiLanguageNpcData['cn'][66059] = {name = "禾·软足", subname = nil}
MultiLanguageNpcData['cn'][66061] = {name = "安济·秋光", subname = nil}
MultiLanguageNpcData['cn'][66064] = {name = "调酒师拓莫若", subname = "旅店老板"}
MultiLanguageNpcData['cn'][66065] = {name = "涂大厨", subname = nil}
MultiLanguageNpcData['cn'][66066] = {name = "烈日行者德兹科", subname = "逐晨者酋长"}
MultiLanguageNpcData['cn'][66067] = {name = "远古打击符文", subname = nil}
MultiLanguageNpcData['cn'][66072] = {name = "昆莱难民 01", subname = nil}
MultiLanguageNpcData['cn'][66074] = {name = "昆莱难民 02", subname = nil}
MultiLanguageNpcData['cn'][66095] = {name = "深蕨表弟", subname = nil}
MultiLanguageNpcData['cn'][66126] = {name = "祖塔", subname = "热情的宠物训练师"}
MultiLanguageNpcData['cn'][66135] = {name = "凶狠的达戈", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66136] = {name = "安纳林", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66137] = {name = "嗜虐的索亚", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66142] = {name = "古拉巴什迅猛龙", subname = nil}
MultiLanguageNpcData['cn'][66165] = {name = "阿曼尼散兵", subname = "赞达拉入侵者"}
MultiLanguageNpcData['cn'][66169] = {name = "法拉基苦行僧", subname = "赞达拉入侵者"}
MultiLanguageNpcData['cn'][66172] = {name = "秋英花幼苗", subname = nil}
MultiLanguageNpcData['cn'][66174] = {name = "法拉基流浪者", subname = "赞达拉入侵者"}
MultiLanguageNpcData['cn'][66182] = {name = "古拉巴什追猎者", subname = "赞达拉入侵者"}
MultiLanguageNpcData['cn'][66183] = {name = "炮舰炮台", subname = nil}
MultiLanguageNpcData['cn'][66190] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66199] = {name = "林·苹花", subname = "酒师"}
MultiLanguageNpcData['cn'][66200] = {name = "雷霆要塞士兵", subname = nil}
MultiLanguageNpcData['cn'][66202] = {name = "雷霆要塞工人", subname = nil}
MultiLanguageNpcData['cn'][66203] = {name = "雷霆要塞加农炮", subname = nil}
MultiLanguageNpcData['cn'][66205] = {name = "谷仓破坏者", subname = nil}
MultiLanguageNpcData['cn'][66206] = {name = "魔古渗透者", subname = nil}
MultiLanguageNpcData['cn'][66210] = {name = "雷霆要塞炸药桶", subname = nil}
MultiLanguageNpcData['cn'][66212] = {name = "巨魔高阶牧师", subname = nil}
MultiLanguageNpcData['cn'][66213] = {name = "扣扣", subname = nil}
MultiLanguageNpcData['cn'][66214] = {name = "担惊受怕的农场帮工", subname = nil}
MultiLanguageNpcData['cn'][66215] = {name = "Beer Bunny", subname = nil}
MultiLanguageNpcData['cn'][66217] = {name = "塞特·蜜露", subname = nil}
MultiLanguageNpcData['cn'][66218] = {name = "佟洛", subname = nil}
MultiLanguageNpcData['cn'][66219] = {name = "敏捷的寇法", subname = "箭商"}
MultiLanguageNpcData['cn'][66220] = {name = "蜜露村长", subname = nil}
MultiLanguageNpcData['cn'][66222] = {name = "穆尔长老", subname = "急救训练师"}
MultiLanguageNpcData['cn'][66223] = {name = "蜜掌长老", subname = "商人"}
MultiLanguageNpcData['cn'][66226] = {name = "送酒员", subname = nil}
MultiLanguageNpcData['cn'][66228] = {name = "毕涛", subname = nil}
MultiLanguageNpcData['cn'][66230] = {name = "苏米", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][66235] = {name = "守田者茅", subname = nil}
MultiLanguageNpcData['cn'][66236] = {name = "酒坊老板娘奇奇", subname = "旅店老板"}
MultiLanguageNpcData['cn'][66237] = {name = "活泼的坎", subname = nil}
MultiLanguageNpcData['cn'][66238] = {name = "吴鹤鸣", subname = "杂货商"}
MultiLanguageNpcData['cn'][66241] = {name = "驯兽师卡玛", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][66244] = {name = "驯兽师苏明", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][66245] = {name = "骑羊人尼克尼克", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][66247] = {name = "驯虎师刘多", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][66249] = {name = "驯马人金姆", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][66251] = {name = "女猎手维尔耶丽", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][66261] = {name = "赞达拉勇士", subname = nil}
MultiLanguageNpcData['cn'][66262] = {name = "奉献", subname = nil}
MultiLanguageNpcData['cn'][66265] = {name = "孙庐穹", subname = nil}
MultiLanguageNpcData['cn'][66268] = {name = "加图勒召焰者", subname = nil}
MultiLanguageNpcData['cn'][66269] = {name = "双塔步兵", subname = nil}
MultiLanguageNpcData['cn'][66270] = {name = "邪风术士", subname = nil}
MultiLanguageNpcData['cn'][66271] = {name = "邪风召唤师", subname = nil}
MultiLanguageNpcData['cn'][66272] = {name = "双塔亡灵卫士", subname = nil}
MultiLanguageNpcData['cn'][66273] = {name = "双塔投石手", subname = nil}
MultiLanguageNpcData['cn'][66275] = {name = "贝兰德拉·邪风", subname = nil}
MultiLanguageNpcData['cn'][66277] = {name = "克胡达葛布", subname = nil}
MultiLanguageNpcData['cn'][66278] = {name = "野鬼", subname = nil}
MultiLanguageNpcData['cn'][66279] = {name = "双塔投石车", subname = nil}
MultiLanguageNpcData['cn'][66281] = {name = "菲克索尔·孤心", subname = nil}
MultiLanguageNpcData['cn'][66283] = {name = "多伦上尉", subname = nil}
MultiLanguageNpcData['cn'][66284] = {name = "雷霆要塞工人", subname = nil}
MultiLanguageNpcData['cn'][66285] = {name = "雷霆要塞步兵", subname = nil}
MultiLanguageNpcData['cn'][66286] = {name = "雷霆要塞修理工", subname = nil}
MultiLanguageNpcData['cn'][66287] = {name = "雷霆要塞中尉", subname = nil}
MultiLanguageNpcData['cn'][66288] = {name = "雷霆要塞神枪手", subname = nil}
MultiLanguageNpcData['cn'][66289] = {name = "奥苏尔喷火者", subname = nil}
MultiLanguageNpcData['cn'][66291] = {name = "雷霆要塞士兵", subname = nil}
MultiLanguageNpcData['cn'][66292] = {name = "空军上将罗杰斯", subname = nil}
MultiLanguageNpcData['cn'][66293] = {name = "粉白骑乘仙鹤", subname = nil}
MultiLanguageNpcData['cn'][66298] = {name = "绿色龙龟", subname = nil}
MultiLanguageNpcData['cn'][66300] = {name = "天火号士兵", subname = nil}
MultiLanguageNpcData['cn'][66306] = {name = "黑爪密探", subname = "黑王子的仆从"}
MultiLanguageNpcData['cn'][66307] = {name = "Flame Bunny", subname = nil}
MultiLanguageNpcData['cn'][66308] = {name = "雷霆要塞军火", subname = nil}
MultiLanguageNpcData['cn'][66309] = {name = "刃鳞开膛者", subname = nil}
MultiLanguageNpcData['cn'][66315] = {name = "山泽缚石者", subname = nil}
MultiLanguageNpcData['cn'][66320] = {name = "雷霆要塞炸药", subname = nil}
MultiLanguageNpcData['cn'][66326] = {name = "结实的阿洛", subname = nil}
MultiLanguageNpcData['cn'][66328] = {name = "扎佐·耀指", subname = "黑王子密探"}
MultiLanguageNpcData['cn'][66336] = {name = "Thunder Hold Fire Effects Bunny", subname = nil}
MultiLanguageNpcData['cn'][66346] = {name = "黑爪卫士", subname = "黑王子的仆从"}
MultiLanguageNpcData['cn'][66347] = {name = "黑爪密探", subname = "黑王子的仆从"}
MultiLanguageNpcData['cn'][66348] = {name = "雷霆要塞武士", subname = nil}
MultiLanguageNpcData['cn'][66349] = {name = "古拉巴什蝙蝠骑士", subname = "赞达拉入侵者"}
MultiLanguageNpcData['cn'][66352] = {name = "叛徒格鲁克", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66356] = {name = "黄师傅", subname = "禅杖商"}
MultiLanguageNpcData['cn'][66365] = {name = "翡翠触须", subname = nil}
MultiLanguageNpcData['cn'][66366] = {name = "被俘的熊猫人幼崽", subname = nil}
MultiLanguageNpcData['cn'][66367] = {name = "加图尔之眼", subname = nil}
MultiLanguageNpcData['cn'][66368] = {name = "食腐秃鹫", subname = nil}
MultiLanguageNpcData['cn'][66370] = {name = "罗杰斯上将的私人旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66372] = {name = "梅达·硬蹄", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66380] = {name = "迅捷陷阱", subname = nil}
MultiLanguageNpcData['cn'][66391] = {name = "科里克提克腺体追迹者", subname = nil}
MultiLanguageNpcData['cn'][66394] = {name = "雷霆要塞加农炮", subname = nil}
MultiLanguageNpcData['cn'][66395] = {name = "雷霆要塞炮手", subname = nil}
MultiLanguageNpcData['cn'][66398] = {name = "加尔鲁什尔步兵", subname = nil}
MultiLanguageNpcData['cn'][66410] = {name = "生命之魂", subname = nil}
MultiLanguageNpcData['cn'][66411] = {name = "水流之魂", subname = nil}
MultiLanguageNpcData['cn'][66412] = {name = "艾琳娜·振翼", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66415] = {name = "商人秋兴", subname = nil}
MultiLanguageNpcData['cn'][66419] = {name = "蟠龙脊神射手", subname = nil}
MultiLanguageNpcData['cn'][66422] = {name = "卡桑德拉·卡布", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66425] = {name = "徘徊煞魔", subname = nil}
MultiLanguageNpcData['cn'][66426] = {name = "煞魔先驱", subname = nil}
MultiLanguageNpcData['cn'][66430] = {name = "伊桑·墓裔", subname = "部落法师"}
MultiLanguageNpcData['cn'][66432] = {name = "部落战车", subname = nil}
MultiLanguageNpcData['cn'][66433] = {name = "天火号旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66436] = {name = "杰出的高雷兹勒", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66437] = {name = "奥术师许云", subname = "部落法师"}
MultiLanguageNpcData['cn'][66442] = {name = "佐尔坦", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66446] = {name = "雷霆要塞修理工", subname = nil}
MultiLanguageNpcData['cn'][66448] = {name = "隐秘蜥蜴", subname = nil}
MultiLanguageNpcData['cn'][66452] = {name = "科拉·恐怖图腾", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66459] = {name = "加尔鲁什尔粉碎者", subname = nil}
MultiLanguageNpcData['cn'][66460] = {name = "天火号旋翼机飞行员", subname = nil}
MultiLanguageNpcData['cn'][66464] = {name = "金尼", subname = nil}
MultiLanguageNpcData['cn'][66465] = {name = "伊克提克虫巢卫士", subname = nil}
MultiLanguageNpcData['cn'][66466] = {name = "“冷血”崔克斯", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66472] = {name = "钳爪王蟹", subname = nil}
MultiLanguageNpcData['cn'][66473] = {name = "天火号旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66477] = {name = "Thunder Hold Cannon Fire Effects Bunny", subname = nil}
MultiLanguageNpcData['cn'][66478] = {name = "大卫·寇斯", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66484] = {name = "雷霆要塞工人", subname = nil}
MultiLanguageNpcData['cn'][66503] = {name = "雷霆要塞步兵", subname = nil}
MultiLanguageNpcData['cn'][66505] = {name = "雷霆要塞武士", subname = nil}
MultiLanguageNpcData['cn'][66506] = {name = "雷霆要塞炮手", subname = nil}
MultiLanguageNpcData['cn'][66507] = {name = "雷霆要塞神枪手", subname = nil}
MultiLanguageNpcData['cn'][66512] = {name = "德扎·疫角", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66513] = {name = "昆森咸湿怪客", subname = nil}
MultiLanguageNpcData['cn'][66515] = {name = "科塔兹·黑锤", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66518] = {name = "伊芙瑞莎", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66520] = {name = "杜林·黑锤", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66522] = {name = "莉迪亚·埃考斯特", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66529] = {name = "失窃酒桶", subname = nil}
MultiLanguageNpcData['cn'][66549] = {name = "废土牦牛", subname = nil}
MultiLanguageNpcData['cn'][66550] = {name = "尼基·微技", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66551] = {name = "拉斯安", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66552] = {name = "纳洛克", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66553] = {name = "莫勒鲁长老", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66554] = {name = "联盟路障", subname = nil}
MultiLanguageNpcData['cn'][66555] = {name = "联盟路障", subname = nil}
MultiLanguageNpcData['cn'][66556] = {name = "联盟路障", subname = nil}
MultiLanguageNpcData['cn'][66557] = {name = "血骑士安塔里", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66561] = {name = "戈玛·阿桑", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66565] = {name = "极重伤的飞行员", subname = nil}
MultiLanguageNpcData['cn'][66570] = {name = "法拉基刺客", subname = "赞达拉入侵者"}
MultiLanguageNpcData['cn'][66571] = {name = "Barricade 1 Missile Bunny", subname = nil}
MultiLanguageNpcData['cn'][66572] = {name = "Barricade 1 Explode Bunny", subname = nil}
MultiLanguageNpcData['cn'][66577] = {name = "Barricade 2 Missile Bunny", subname = nil}
MultiLanguageNpcData['cn'][66579] = {name = "寡妇幼蛛", subname = nil}
MultiLanguageNpcData['cn'][66580] = {name = "蜘蛛", subname = nil}
MultiLanguageNpcData['cn'][66583] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][66587] = {name = "蓬松毛", subname = nil}
MultiLanguageNpcData['cn'][66595] = {name = "废土小牛", subname = nil}
MultiLanguageNpcData['cn'][66596] = {name = "格里兹·怨掌", subname = nil}
MultiLanguageNpcData['cn'][66601] = {name = "烈焰之子", subname = nil}
MultiLanguageNpcData['cn'][66603] = {name = "利尔·夜风", subname = "军情七处"}
MultiLanguageNpcData['cn'][66633] = {name = "鲁克提", subname = nil}
MultiLanguageNpcData['cn'][66634] = {name = "地狱咆哮的先锋战士", subname = nil}
MultiLanguageNpcData['cn'][66635] = {name = "毕格·爆索", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66636] = {name = "差点没头的雅各布", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66638] = {name = "奥克鲁特·荒龙", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66639] = {name = "格特瑞奇", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66640] = {name = "垂降绳索", subname = nil}
MultiLanguageNpcData['cn'][66641] = {name = "天火号士兵", subname = nil}
MultiLanguageNpcData['cn'][66643] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66644] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][66646] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66647] = {name = "雷霆要塞神枪手", subname = nil}
MultiLanguageNpcData['cn'][66648] = {name = "雷霆要塞中尉", subname = nil}
MultiLanguageNpcData['cn'][66649] = {name = "雷霆要塞修理工", subname = nil}
MultiLanguageNpcData['cn'][66650] = {name = "雷霆要塞步兵", subname = nil}
MultiLanguageNpcData['cn'][66651] = {name = "雷霆要塞工人", subname = nil}
MultiLanguageNpcData['cn'][66654] = {name = "雷霆要塞补给品", subname = nil}
MultiLanguageNpcData['cn'][66656] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66657] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][66658] = {name = "孤独的乔吉", subname = nil}
MultiLanguageNpcData['cn'][66659] = {name = "温和的薛极", subname = nil}
MultiLanguageNpcData['cn'][66660] = {name = "艾利·蜜掌", subname = nil}
MultiLanguageNpcData['cn'][66662] = {name = "季鸥", subname = nil}
MultiLanguageNpcData['cn'][66663] = {name = "螳螂妖飞行者", subname = nil}
MultiLanguageNpcData['cn'][66664] = {name = "温驯幼龙", subname = nil}
MultiLanguageNpcData['cn'][66665] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][66666] = {name = "坡东防御者", subname = nil}
MultiLanguageNpcData['cn'][66667] = {name = "利维特·急刹", subname = nil}
MultiLanguageNpcData['cn'][66668] = {name = "染煞徘徊者", subname = nil}
MultiLanguageNpcData['cn'][66669] = {name = "荒龙奴役者", subname = nil}
MultiLanguageNpcData['cn'][66670] = {name = "佩妮猪", subname = nil}
MultiLanguageNpcData['cn'][66671] = {name = "挑食猪", subname = nil}
MultiLanguageNpcData['cn'][66672] = {name = "烂泥猪", subname = nil}
MultiLanguageNpcData['cn'][66673] = {name = "笨笨猪", subname = nil}
MultiLanguageNpcData['cn'][66674] = {name = "炮舰炮台", subname = nil}
MultiLanguageNpcData['cn'][66675] = {name = "派恩少校", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66676] = {name = "炮舰炮台", subname = nil}
MultiLanguageNpcData['cn'][66677] = {name = "炮舰炮台", subname = nil}
MultiLanguageNpcData['cn'][66678] = {name = "克里斯托", subname = "祥和之灵商人"}
MultiLanguageNpcData['cn'][66679] = {name = "匿踪大师琪麟", subname = nil}
MultiLanguageNpcData['cn'][66680] = {name = "利维特·急刹", subname = nil}
MultiLanguageNpcData['cn'][66681] = {name = "格罗克中士", subname = nil}
MultiLanguageNpcData['cn'][66682] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66683] = {name = "夏琪亚", subname = nil}
MultiLanguageNpcData['cn'][66684] = {name = "商人金宝", subname = nil}
MultiLanguageNpcData['cn'][66685] = {name = "达奇", subname = "祥和之灵商人"}
MultiLanguageNpcData['cn'][66687] = {name = "蜘蛛卵", subname = nil}
MultiLanguageNpcData['cn'][66688] = {name = "煞魔触须", subname = nil}
MultiLanguageNpcData['cn'][66689] = {name = "梅琴乐", subname = nil}
MultiLanguageNpcData['cn'][66690] = {name = "点灯人老穆", subname = nil}
MultiLanguageNpcData['cn'][66691] = {name = "艾兹瑞尔", subname = nil}
MultiLanguageNpcData['cn'][66692] = {name = "萨姆斯", subname = nil}
MultiLanguageNpcData['cn'][66693] = {name = "赞达拉领主", subname = nil}
MultiLanguageNpcData['cn'][66694] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66697] = {name = "利尔·夜风", subname = "军情七处"}
MultiLanguageNpcData['cn'][66699] = {name = "Generic Invisible Stalker Controller NonImmune - IH", subname = nil}
MultiLanguageNpcData['cn'][66700] = {name = "赞达拉占卜师", subname = nil}
MultiLanguageNpcData['cn'][66705] = {name = "云游的主祭", subname = nil}
MultiLanguageNpcData['cn'][66717] = {name = "兽语者吱吱", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][66727] = {name = "科里克提克渗透者", subname = nil}
MultiLanguageNpcData['cn'][66730] = {name = "圣地的俞娜", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66732] = {name = "海特大师", subname = "大师"}
MultiLanguageNpcData['cn'][66733] = {name = "莫鲁克", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66734] = {name = "农夫倪石", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66738] = {name = "勇敢的尹勇", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66739] = {name = "废土行者苏游", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66741] = {name = "天选者亚济", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66742] = {name = "Thunder Hold Fire Effects Bunny - Scorched Ground", subname = nil}
MultiLanguageNpcData['cn'][66743] = {name = "怀疑", subname = nil}
MultiLanguageNpcData['cn'][66747] = {name = "血池", subname = nil}
MultiLanguageNpcData['cn'][66749] = {name = "云游节灯笼", subname = nil}
MultiLanguageNpcData['cn'][66773] = {name = "毒心者夏克里尔", subname = nil}
MultiLanguageNpcData['cn'][66774] = {name = "至尊者柯尔凡", subname = nil}
MultiLanguageNpcData['cn'][66775] = {name = "掠风者克尔鲁克", subname = nil}
MultiLanguageNpcData['cn'][66776] = {name = "无伤者玛里克", subname = nil}
MultiLanguageNpcData['cn'][66777] = {name = "觅血者斯基尔", subname = nil}
MultiLanguageNpcData['cn'][66778] = {name = "切割者里卡尔", subname = nil}
MultiLanguageNpcData['cn'][66779] = {name = "操纵者卡兹提克", subname = nil}
MultiLanguageNpcData['cn'][66780] = {name = "虫群卫士希赛克", subname = nil}
MultiLanguageNpcData['cn'][66781] = {name = "暴食蝗卡诺兹", subname = nil}
MultiLanguageNpcData['cn'][66782] = {name = "明澈者伊约库克", subname = nil}
MultiLanguageNpcData['cn'][66783] = {name = "阿卡隆", subname = "加拉隆的子嗣"}
MultiLanguageNpcData['cn'][66784] = {name = "夏克提克", subname = nil}
MultiLanguageNpcData['cn'][66785] = {name = "惊怖具象", subname = nil}
MultiLanguageNpcData['cn'][66788] = {name = "瑟拉提克征服者", subname = nil}
MultiLanguageNpcData['cn'][66789] = {name = "科里克提克征服者", subname = nil}
MultiLanguageNpcData['cn'][66790] = {name = "扎尼提克征服者", subname = nil}
MultiLanguageNpcData['cn'][66791] = {name = "皇家宰相佐尔洛克", subname = "女王喉舌"}
MultiLanguageNpcData['cn'][66793] = {name = "地狱咆哮之拳工程师", subname = nil}
MultiLanguageNpcData['cn'][66794] = {name = "琥珀碎片", subname = nil}
MultiLanguageNpcData['cn'][66795] = {name = "Gunship Fire Bunny", subname = nil}
MultiLanguageNpcData['cn'][66796] = {name = "多伦上尉", subname = nil}
MultiLanguageNpcData['cn'][66797] = {name = "无伤者玛里克", subname = nil}
MultiLanguageNpcData['cn'][66798] = {name = "多伦的旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66800] = {name = "掠风者克尔鲁克", subname = nil}
MultiLanguageNpcData['cn'][66803] = {name = "鲁克提暗影追猎者", subname = nil}
MultiLanguageNpcData['cn'][66815] = {name = "鲍丁·固拳", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66818] = {name = "剧毒河豚", subname = nil}
MultiLanguageNpcData['cn'][66819] = {name = "布洛克", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66822] = {name = "高兹·怨怒", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66824] = {name = "奥巴里斯", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66825] = {name = "艾利·蜜掌", subname = nil}
MultiLanguageNpcData['cn'][66838] = {name = "林凯·蜜露", subname = nil}
MultiLanguageNpcData['cn'][66840] = {name = "Brew bunny", subname = nil}
MultiLanguageNpcData['cn'][66841] = {name = "林凯·蜜露", subname = nil}
MultiLanguageNpcData['cn'][66843] = {name = "掩埋的螳螂妖尸体", subname = nil}
MultiLanguageNpcData['cn'][66845] = {name = "格罗克中士", subname = nil}
MultiLanguageNpcData['cn'][66847] = {name = "夏琪亚", subname = nil}
MultiLanguageNpcData['cn'][66848] = {name = "艾利·蜜掌", subname = nil}
MultiLanguageNpcData['cn'][66849] = {name = "科沃克", subname = nil}
MultiLanguageNpcData['cn'][66850] = {name = "千年守护者", subname = nil}
MultiLanguageNpcData['cn'][66851] = {name = "聚合之恐", subname = nil}
MultiLanguageNpcData['cn'][66853] = {name = "林凯·蜜露", subname = nil}
MultiLanguageNpcData['cn'][66855] = {name = "利尔·夜风", subname = "军情七处"}
MultiLanguageNpcData['cn'][66856] = {name = "空军上将罗杰斯", subname = nil}
MultiLanguageNpcData['cn'][66857] = {name = "Parachute Bunny", subname = nil}
MultiLanguageNpcData['cn'][66865] = {name = "碧克斯·投弹", subname = nil}
MultiLanguageNpcData['cn'][66866] = {name = "瘢牙", subname = nil}
MultiLanguageNpcData['cn'][66870] = {name = "季鸥", subname = nil}
MultiLanguageNpcData['cn'][66871] = {name = "智者威利", subname = nil}
MultiLanguageNpcData['cn'][66872] = {name = "暴怒的范毅", subname = nil}
MultiLanguageNpcData['cn'][66875] = {name = "无伤者玛里克", subname = nil}
MultiLanguageNpcData['cn'][66876] = {name = "泰勒·斯托克顿", subname = nil}
MultiLanguageNpcData['cn'][66880] = {name = "湖泊阔步者", subname = nil}
MultiLanguageNpcData['cn'][66881] = {name = "谷地阔步者", subname = nil}
MultiLanguageNpcData['cn'][66882] = {name = "海洋阔步者", subname = nil}
MultiLanguageNpcData['cn'][66888] = {name = "Thunder Hold Conversation Bunny", subname = nil}
MultiLanguageNpcData['cn'][66891] = {name = "泽地阔步者", subname = nil}
MultiLanguageNpcData['cn'][66893] = {name = "曼弗雷德", subname = nil}
MultiLanguageNpcData['cn'][66894] = {name = "曼弗雷德", subname = nil}
MultiLanguageNpcData['cn'][66896] = {name = "铁腕旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66897] = {name = "铁腕旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66900] = {name = "心灵看守者胡戈伦", subname = nil}
MultiLanguageNpcData['cn'][66902] = {name = "利维特·急刹", subname = nil}
MultiLanguageNpcData['cn'][66904] = {name = "炮台", subname = nil}
MultiLanguageNpcData['cn'][66905] = {name = "熊猫人炮手", subname = nil}
MultiLanguageNpcData['cn'][66911] = {name = "罗布·悲鸣", subname = nil}
MultiLanguageNpcData['cn'][66913] = {name = "Stormwind to Pandatia - Alliance intro Scene - CLIENT-SIDE - JSB", subname = nil}
MultiLanguageNpcData['cn'][66915] = {name = "库卡隆精英", subname = nil}
MultiLanguageNpcData['cn'][66916] = {name = "Hozen Dangler VEHICLE", subname = nil}
MultiLanguageNpcData['cn'][66917] = {name = "猢狲震地者", subname = nil}
MultiLanguageNpcData['cn'][66918] = {name = "探索者祖什", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66919] = {name = "“腌菜”苏利·麦克莱利", subname = "军情七处"}
MultiLanguageNpcData['cn'][66920] = {name = "堕落的祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][66921] = {name = "米希卡", subname = "军情七处"}
MultiLanguageNpcData['cn'][66922] = {name = "安玻·吉尔妮", subname = "军情七处"}
MultiLanguageNpcData['cn'][66924] = {name = "尼姆·杰码", subname = "军情七处"}
MultiLanguageNpcData['cn'][66927] = {name = "诺德·杰码", subname = "军情七处"}
MultiLanguageNpcData['cn'][66928] = {name = "煞魔射手", subname = nil}
MultiLanguageNpcData['cn'][66931] = {name = "暴风城士兵", subname = nil}
MultiLanguageNpcData['cn'][66933] = {name = "基沙克", subname = "科里曼达的之子"}
MultiLanguageNpcData['cn'][66934] = {name = "达姆拉克", subname = "科里曼达的仆从"}
MultiLanguageNpcData['cn'][66936] = {name = "钳爪领主科里曼达", subname = "钳爪之王"}
MultiLanguageNpcData['cn'][66937] = {name = "阿卡拉", subname = "科里曼达之盾"}
MultiLanguageNpcData['cn'][66941] = {name = "喷涌", subname = nil}
MultiLanguageNpcData['cn'][66942] = {name = "徘徊煞魔", subname = nil}
MultiLanguageNpcData['cn'][66948] = {name = "扭曲的躯壳", subname = nil}
MultiLanguageNpcData['cn'][66961] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66968] = {name = "琥珀爆发", subname = nil}
MultiLanguageNpcData['cn'][66973] = {name = "凯·羽落", subname = "凤凰蛋商人"}
MultiLanguageNpcData['cn'][66976] = {name = "阿勒布兰", subname = nil}
MultiLanguageNpcData['cn'][66992] = {name = "灵魂撕裂者", subname = nil}
MultiLanguageNpcData['cn'][66993] = {name = "海伦娜·斯坦顿", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][67003] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][67009] = {name = "武僧门徒", subname = nil}
MultiLanguageNpcData['cn'][67010] = {name = "Psycho Mantid: Tik vs Kree'zot Bunny", subname = nil}
MultiLanguageNpcData['cn'][67011] = {name = "加尔鲁什尔步兵", subname = nil}
MultiLanguageNpcData['cn'][67016] = {name = "古代雕像躯干", subname = nil}
MultiLanguageNpcData['cn'][67017] = {name = "古代雕像手臂", subname = nil}
MultiLanguageNpcData['cn'][67018] = {name = "古代雕像头颅", subname = nil}
MultiLanguageNpcData['cn'][67019] = {name = "古代雕像肩膀", subname = nil}
MultiLanguageNpcData['cn'][67032] = {name = "炮舰炮台", subname = nil}
MultiLanguageNpcData['cn'][67038] = {name = "地狱咆哮之拳工程师", subname = nil}
MultiLanguageNpcData['cn'][67040] = {name = "地狱咆哮之拳码头工人", subname = nil}
MultiLanguageNpcData['cn'][67058] = {name = "四风商贩", subname = nil}
MultiLanguageNpcData['cn'][67059] = {name = "四风商贩", subname = nil}
MultiLanguageNpcData['cn'][67060] = {name = "程大师", subname = nil}
MultiLanguageNpcData['cn'][67063] = {name = "天火号轰炸机", subname = nil}
MultiLanguageNpcData['cn'][67064] = {name = "Paragon Chat Controller", subname = nil}
MultiLanguageNpcData['cn'][67065] = {name = "商路土地精", subname = nil}
MultiLanguageNpcData['cn'][67067] = {name = "利尔的旋翼机", subname = nil}
MultiLanguageNpcData['cn'][67068] = {name = "利尔的旋翼机", subname = nil}
MultiLanguageNpcData['cn'][67071] = {name = "机警的森林徘徊者", subname = nil}
MultiLanguageNpcData['cn'][67084] = {name = "巨型迅足虫", subname = nil}
MultiLanguageNpcData['cn'][67090] = {name = "熊猫人志愿者", subname = nil}
MultiLanguageNpcData['cn'][67091] = {name = "切割者里卡尔", subname = nil}
MultiLanguageNpcData['cn'][67093] = {name = "希克提克助战者", subname = nil}
MultiLanguageNpcData['cn'][67094] = {name = "风之优雅", subname = nil}
MultiLanguageNpcData['cn'][67099] = {name = "苏库拉", subname = "水噬寡妇"}
MultiLanguageNpcData['cn'][67125] = {name = "雷鳃", subname = nil}
MultiLanguageNpcData['cn'][67129] = {name = "攀爬的曼弗雷德", subname = nil}
MultiLanguageNpcData['cn'][67131] = {name = "地狱咆哮的先锋战士", subname = nil}
MultiLanguageNpcData['cn'][67136] = {name = "爆裂曼弗雷德", subname = nil}
MultiLanguageNpcData['cn'][67158] = {name = "库卡隆精英", subname = nil}
MultiLanguageNpcData['cn'][67159] = {name = "白虎寺武僧", subname = nil}
MultiLanguageNpcData['cn'][67160] = {name = "卡拉克西巢穴卫士", subname = nil}
MultiLanguageNpcData['cn'][67168] = {name = "海军上将泰勒", subname = nil}
MultiLanguageNpcData['cn'][67170] = {name = "塑铁者彭金", subname = nil}
MultiLanguageNpcData['cn'][67171] = {name = "勇敢的林利", subname = "供应商"}
MultiLanguageNpcData['cn'][67176] = {name = "护甲匠小刚", subname = "修理"}
MultiLanguageNpcData['cn'][67183] = {name = "庇护所供应商安和", subname = "修理"}
MultiLanguageNpcData['cn'][67185] = {name = "供应商菲尔普斯", subname = "供应商"}
MultiLanguageNpcData['cn'][67186] = {name = "供应商卓歌", subname = "供应商"}
MultiLanguageNpcData['cn'][67195] = {name = "半山防御者", subname = nil}
MultiLanguageNpcData['cn'][67196] = {name = "狂怒的半山防御者", subname = nil}
MultiLanguageNpcData['cn'][67197] = {name = "渔人码头守卫", subname = nil}
MultiLanguageNpcData['cn'][67221] = {name = "陶俑首领", subname = nil}
MultiLanguageNpcData['cn'][67231] = {name = "君王的试炼", subname = nil}
MultiLanguageNpcData['cn'][67236] = {name = "摧心魔", subname = nil}
MultiLanguageNpcData['cn'][67249] = {name = "熊猫人奴隶", subname = "熊猫人奴隶"}
MultiLanguageNpcData['cn'][67250] = {name = "利维特·急刹", subname = nil}
MultiLanguageNpcData['cn'][67252] = {name = "匿踪大师琪麟", subname = nil}
MultiLanguageNpcData['cn'][67281] = {name = "上油工人", subname = nil}
MultiLanguageNpcData['cn'][67304] = {name = "神盾步兵", subname = nil}
MultiLanguageNpcData['cn'][67334] = {name = "血柄荣誉卫士", subname = "血柄荣誉卫士"}
MultiLanguageNpcData['cn'][67344] = {name = "迅捷灰狼", subname = nil}
MultiLanguageNpcData['cn'][67359] = {name = "天火号旋翼机X2型", subname = nil}
MultiLanguageNpcData['cn'][67370] = {name = "杰里米·费舍尔", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][67386] = {name = "空军上将罗杰斯", subname = nil}
MultiLanguageNpcData['cn'][67387] = {name = "工匠大师欧沃斯巴克", subname = "侏儒工程学首席技师"}
MultiLanguageNpcData['cn'][67395] = {name = "滩头歼灭者", subname = nil}
MultiLanguageNpcData['cn'][67461] = {name = "血柄督军", subname = nil}
MultiLanguageNpcData['cn'][67493] = {name = "自动攻城器4000型", subname = nil}
MultiLanguageNpcData['cn'][67496] = {name = "自动干扰器9000型", subname = nil}
MultiLanguageNpcData['cn'][67560] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][67607] = {name = "终极科普罗德2500型", subname = "限量版"}
MultiLanguageNpcData['cn'][67615] = {name = "堆叠式雄鹿", subname = nil}
MultiLanguageNpcData['cn'][67634] = {name = "Well Supplied Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67666] = {name = "Well Fed Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67672] = {name = "瓦萨林·赤晨", subname = "夺日者先锋军军需官"}
MultiLanguageNpcData['cn'][67679] = {name = "锦绣阔步者", subname = nil}
MultiLanguageNpcData['cn'][67687] = {name = "特攻队指挥官", subname = nil}
MultiLanguageNpcData['cn'][67733] = {name = "Inspired Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67761] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][67765] = {name = "天火号旋翼机飞行员", subname = nil}
MultiLanguageNpcData['cn'][67768] = {name = "沼泽欢跳者", subname = nil}
MultiLanguageNpcData['cn'][67771] = {name = "珀光萤火虫", subname = nil}
MultiLanguageNpcData['cn'][67801] = {name = "大元帅双辫", subname = nil}
MultiLanguageNpcData['cn'][67808] = {name = "JINYU Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][67817] = {name = "Bubble Trap Vehicle", subname = nil}
MultiLanguageNpcData['cn'][67822] = {name = "雄狮港精兵", subname = nil}
MultiLanguageNpcData['cn'][67867] = {name = "加尔鲁什·地狱咆哮", subname = "酋长"}
MultiLanguageNpcData['cn'][67897] = {name = "侏儒飞行器", subname = nil}
MultiLanguageNpcData['cn'][67936] = {name = "GNOME Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][67938] = {name = "Well Lubricated Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67941] = {name = "油腻的蛇", subname = nil}
MultiLanguageNpcData['cn'][67959] = {name = "工匠大师欧沃斯巴克", subname = "侏儒工程学首席技师"}
MultiLanguageNpcData['cn'][67961] = {name = "GNOME Gadget Bunny", subname = nil}
MultiLanguageNpcData['cn'][67967] = {name = "神盾机械碾压者", subname = nil}
MultiLanguageNpcData['cn'][67973] = {name = "吉恩·格雷迈恩", subname = nil}
MultiLanguageNpcData['cn'][67975] = {name = "Inspired Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67976] = {name = "工匠大师欧沃斯巴克", subname = "侏儒工程学首席技师"}
MultiLanguageNpcData['cn'][68000] = {name = "海伦·慧歌", subname = "肯瑞托远征军军需官"}
MultiLanguageNpcData['cn'][68003] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['cn'][68004] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68005] = {name = "青玉战神", subname = nil}
MultiLanguageNpcData['cn'][68018] = {name = "裘碧卡·碎影", subname = "恶魔学识大师"}
MultiLanguageNpcData['cn'][68019] = {name = "坎雷萨德·埃伯洛克", subname = "黑暗收割领袖"}
MultiLanguageNpcData['cn'][68025] = {name = "萨尔", subname = nil}
MultiLanguageNpcData['cn'][68038] = {name = "阿格娜", subname = nil}
MultiLanguageNpcData['cn'][68052] = {name = "夺日者平民", subname = nil}
MultiLanguageNpcData['cn'][68059] = {name = "萨尔", subname = nil}
MultiLanguageNpcData['cn'][68084] = {name = "洛瑟玛·塞隆", subname = "奎尔萨拉斯的摄政王"}
MultiLanguageNpcData['cn'][68098] = {name = "灰舌工人", subname = nil}
MultiLanguageNpcData['cn'][68101] = {name = "DWARF Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][68103] = {name = "Inspired Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68106] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68108] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68116] = {name = "Loaded for Bear Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68138] = {name = "火箭鸡", subname = nil}
MultiLanguageNpcData['cn'][68145] = {name = "军团萨特", subname = nil}
MultiLanguageNpcData['cn'][68147] = {name = "伊利达雷萨特", subname = nil}
MultiLanguageNpcData['cn'][68150] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68151] = {name = "秩序精华", subname = nil}
MultiLanguageNpcData['cn'][68210] = {name = "矮人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68213] = {name = "工作完成", subname = nil}
MultiLanguageNpcData['cn'][68214] = {name = "锦鱼人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68231] = {name = "旋转巨龙", subname = nil}
MultiLanguageNpcData['cn'][68232] = {name = "旋转狮鹫", subname = nil}
MultiLanguageNpcData['cn'][68233] = {name = "旋转鱼人", subname = nil}
MultiLanguageNpcData['cn'][68235] = {name = "吉恩·格雷迈恩", subname = nil}
MultiLanguageNpcData['cn'][68238] = {name = "旋转火箭", subname = nil}
MultiLanguageNpcData['cn'][68239] = {name = "旋转飞龙", subname = nil}
MultiLanguageNpcData['cn'][68241] = {name = "感染煞能的野牛人", subname = nil}
MultiLanguageNpcData['cn'][68263] = {name = "熊猫人焰火", subname = nil}
MultiLanguageNpcData['cn'][68278] = {name = "洛瑟玛·塞隆", subname = "奎尔萨拉斯的摄政王"}
MultiLanguageNpcData['cn'][68287] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][68289] = {name = "克希利", subname = nil}
MultiLanguageNpcData['cn'][68303] = {name = "PANDAREN Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][68324] = {name = "Hair of the Dog Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68327] = {name = "暴躁萤火虫", subname = nil}
MultiLanguageNpcData['cn'][68330] = {name = "Cauldron Bunny", subname = nil}
MultiLanguageNpcData['cn'][68357] = {name = "单简", subname = "寇茹军领"}
MultiLanguageNpcData['cn'][68358] = {name = "织恐者阿瓦图", subname = nil}
MultiLanguageNpcData['cn'][68359] = {name = "Pandaren ASLEEP Bunny", subname = nil}
MultiLanguageNpcData['cn'][68396] = {name = "岩石", subname = nil}
MultiLanguageNpcData['cn'][68402] = {name = "狄珂", subname = "售票员"}
MultiLanguageNpcData['cn'][68407] = {name = "“橄榄”小雅", subname = nil}
MultiLanguageNpcData['cn'][68412] = {name = "Iron Fisted Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68415] = {name = "Crypt Bunny", subname = nil}
MultiLanguageNpcData['cn'][68462] = {name = "熊猫人流水之灵", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][68463] = {name = "熊猫人烈焰之灵", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][68464] = {name = "熊猫人微风之灵", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][68465] = {name = "熊猫人雷霆之灵", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][68474] = {name = "指挥官斯卡戈什", subname = nil}
MultiLanguageNpcData['cn'][68477] = {name = "库卡隆哨兵", subname = nil}
MultiLanguageNpcData['cn'][68482] = {name = "银月学者", subname = nil}
MultiLanguageNpcData['cn'][68491] = {name = "暗月陆行鸟", subname = nil}
MultiLanguageNpcData['cn'][68492] = {name = "“微尘”布兰顿", subname = "陆行鸟管理员"}
MultiLanguageNpcData['cn'][68500] = {name = "Heavy Metal Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68509] = {name = "火箭鸡", subname = nil}
MultiLanguageNpcData['cn'][68511] = {name = "旁白", subname = nil}
MultiLanguageNpcData['cn'][68513] = {name = "鹿齿土拨鼠", subname = nil}
MultiLanguageNpcData['cn'][68518] = {name = "GNOME Trap Bunny", subname = nil}
MultiLanguageNpcData['cn'][68536] = {name = "贾浒克", subname = nil}
MultiLanguageNpcData['cn'][68609] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68612] = {name = "天剑哨兵", subname = nil}
MultiLanguageNpcData['cn'][68613] = {name = "无家可归的夺日者", subname = nil}
MultiLanguageNpcData['cn'][68651] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68652] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68677] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68683] = {name = "NIGHT ELF Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][68689] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68690] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][68702] = {name = "Night Elf Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68749] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68766] = {name = "反抗的夺日者", subname = nil}
MultiLanguageNpcData['cn'][68771] = {name = "重装狮鹫", subname = nil}
MultiLanguageNpcData['cn'][68773] = {name = "重装双足飞龙", subname = nil}
MultiLanguageNpcData['cn'][68776] = {name = "Inspired Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68777] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['cn'][68795] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68812] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68817] = {name = "Finale Controller Bunny", subname = nil}
MultiLanguageNpcData['cn'][68837] = {name = "侏儒飞行器", subname = nil}
MultiLanguageNpcData['cn'][68842] = {name = "泰兰德·语风", subname = "艾露恩的高阶女祭司"}
MultiLanguageNpcData['cn'][68869] = {name = "洛洛", subname = nil}
MultiLanguageNpcData['cn'][68880] = {name = "库卡隆杀戮者", subname = nil}
MultiLanguageNpcData['cn'][68881] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68882] = {name = "加尔鲁什·地狱咆哮", subname = "酋长"}
MultiLanguageNpcData['cn'][68894] = {name = "熊猫人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68895] = {name = "熊猫人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68896] = {name = "暗夜精灵建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68897] = {name = "暗夜精灵建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68898] = {name = "锦鱼人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68899] = {name = "侏儒建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68900] = {name = "侏儒建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68901] = {name = "矮人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68904] = {name = "夙娥", subname = "仇妃"}
MultiLanguageNpcData['cn'][68905] = {name = "露琳", subname = "寂妃"}
MultiLanguageNpcData['cn'][68918] = {name = "Divine Bell Bunny", subname = nil}
MultiLanguageNpcData['cn'][68921] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][68922] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68925] = {name = "年轻的瓦里安·乌瑞恩", subname = nil}
MultiLanguageNpcData['cn'][68927] = {name = "调酒师童福", subname = "旅店老板"}
MultiLanguageNpcData['cn'][68937] = {name = "Finale Controller Bunny", subname = nil}
MultiLanguageNpcData['cn'][68966] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68970] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][68972] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68978] = {name = "夺日者难民", subname = "夺日者难民"}
MultiLanguageNpcData['cn'][68986] = {name = "驯兽师小丽", subname = "兽栏管理员"}
MultiLanguageNpcData['cn'][69018] = {name = "Totally Generic Bunny (JSB)", subname = nil}
MultiLanguageNpcData['cn'][69025] = {name = "指挥官斯卡戈什", subname = nil}
MultiLanguageNpcData['cn'][69026] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][69028] = {name = "Generic Client-Side Bunny", subname = nil}
MultiLanguageNpcData['cn'][69045] = {name = "加尔鲁什", subname = "地狱咆哮之子"}
MultiLanguageNpcData['cn'][69048] = {name = "希尔瓦娜斯·风行者", subname = nil}
MultiLanguageNpcData['cn'][69093] = {name = "恐怖孢子鳞茎", subname = nil}
MultiLanguageNpcData['cn'][69161] = {name = "乌达斯塔", subname = nil}
MultiLanguageNpcData['cn'][69170] = {name = "赞达拉平民", subname = nil}
MultiLanguageNpcData['cn'][69257] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][69294] = {name = "赞达拉血卫士", subname = nil}
MultiLanguageNpcData['cn'][69295] = {name = "赞达拉侍僧", subname = nil}
MultiLanguageNpcData['cn'][69296] = {name = "赞达拉屈魂者", subname = nil}
MultiLanguageNpcData['cn'][69333] = {name = "门徒君思", subname = "火金派军需官"}
MultiLanguageNpcData['cn'][69601] = {name = "重磅炸药", subname = nil}
MultiLanguageNpcData['cn'][69627] = {name = "琥珀寄生虫", subname = nil}
MultiLanguageNpcData['cn'][69651] = {name = "战神阿尔图克拉", subname = nil}
MultiLanguageNpcData['cn'][69652] = {name = "山怖", subname = nil}
MultiLanguageNpcData['cn'][69654] = {name = "雷神", subname = "雷电之王"}
MultiLanguageNpcData['cn'][69680] = {name = "暴风之魂", subname = nil}
MultiLanguageNpcData['cn'][69755] = {name = "战神阿尔图克拉", subname = nil}
MultiLanguageNpcData['cn'][69782] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][69791] = {name = "烈焰之灵", subname = nil}
MultiLanguageNpcData['cn'][69792] = {name = "大地之灵", subname = nil}
MultiLanguageNpcData['cn'][69888] = {name = "莱登", subname = "堕落的暴风守护者"}
MultiLanguageNpcData['cn'][69890] = {name = "蓝色小熊猫", subname = nil}
MultiLanguageNpcData['cn'][69915] = {name = "拉斯塔哈大王", subname = nil}
MultiLanguageNpcData['cn'][69918] = {name = "祖尔", subname = nil}
MultiLanguageNpcData['cn'][69945] = {name = "赞达拉荣誉守卫", subname = nil}
MultiLanguageNpcData['cn'][69946] = {name = "胡提亚", subname = nil}
MultiLanguageNpcData['cn'][69947] = {name = "德古", subname = nil}
MultiLanguageNpcData['cn'][69950] = {name = "纳迦影像", subname = "纳迦影像"}
MultiLanguageNpcData['cn'][70052] = {name = "恶魔灵魂井", subname = nil}
MultiLanguageNpcData['cn'][70084] = {name = "泰瑞纳斯·米奈希尔", subname = nil}
MultiLanguageNpcData['cn'][70116] = {name = "魔古平民", subname = nil}
MultiLanguageNpcData['cn'][70155] = {name = "格里伏塔", subname = "绝世宝物商人"}
MultiLanguageNpcData['cn'][70167] = {name = "马克西莫", subname = nil}
MultiLanguageNpcData['cn'][70168] = {name = "诺亚", subname = nil}
MultiLanguageNpcData['cn'][70171] = {name = "伊洛里克", subname = nil}
MultiLanguageNpcData['cn'][70225] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][70261] = {name = "Placeholder Creature", subname = nil}
MultiLanguageNpcData['cn'][70279] = {name = "茉艾拉·索瑞森", subname = "黑铁执政女王"}
MultiLanguageNpcData['cn'][70301] = {name = "柔爪", subname = "骑术训练师"}
MultiLanguageNpcData['cn'][70335] = {name = "季·火掌", subname = "火金大师"}
MultiLanguageNpcData['cn'][70438] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][70461] = {name = "米莉·绿野", subname = "助理计种员"}
MultiLanguageNpcData['cn'][70473] = {name = "霜鬃猎头者", subname = nil}
MultiLanguageNpcData['cn'][70476] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][70543] = {name = "赞达拉煽动者", subname = nil}
MultiLanguageNpcData['cn'][70626] = {name = "深渊魔", subname = nil}
MultiLanguageNpcData['cn'][70789] = {name = "赞达拉暴怒旗帜", subname = nil}
MultiLanguageNpcData['cn'][70799] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][70921] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][70944] = {name = "睿智的夏璞", subname = nil}
MultiLanguageNpcData['cn'][70945] = {name = "赵福兴", subname = nil}
MultiLanguageNpcData['cn'][70946] = {name = "丁艾岚", subname = nil}
MultiLanguageNpcData['cn'][70947] = {name = "巧匠韩克", subname = nil}
MultiLanguageNpcData['cn'][70948] = {name = "陈樵山", subname = nil}
MultiLanguageNpcData['cn'][70949] = {name = "公孙镝甫", subname = nil}
MultiLanguageNpcData['cn'][70950] = {name = "喜妲", subname = nil}
MultiLanguageNpcData['cn'][70951] = {name = "汤万", subname = nil}
MultiLanguageNpcData['cn'][70968] = {name = "库卡隆好战者", subname = nil}
MultiLanguageNpcData['cn'][70971] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][70972] = {name = "森金村守望者", subname = nil}
MultiLanguageNpcData['cn'][70974] = {name = "神庙大门", subname = nil}
MultiLanguageNpcData['cn'][70978] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][70980] = {name = "先知昊梵舟", subname = nil}
MultiLanguageNpcData['cn'][70986] = {name = "库卡隆将领", subname = nil}
MultiLanguageNpcData['cn'][70989] = {name = "玉珑", subname = "青龙"}
MultiLanguageNpcData['cn'][71003] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71008] = {name = "库卡隆空降兵", subname = nil}
MultiLanguageNpcData['cn'][71029] = {name = "玉珑的挑战之锣", subname = nil}
MultiLanguageNpcData['cn'][71039] = {name = "贫瘠之地车队货车", subname = nil}
MultiLanguageNpcData['cn'][71040] = {name = "贫瘠之地车队科多兽", subname = nil}
MultiLanguageNpcData['cn'][71044] = {name = "基尔里克", subname = nil}
MultiLanguageNpcData['cn'][71063] = {name = "先知昊梵舟", subname = nil}
MultiLanguageNpcData['cn'][71065] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][71066] = {name = "库卡隆监视者", subname = nil}
MultiLanguageNpcData['cn'][71082] = {name = "老爹土笛子", subname = nil}
MultiLanguageNpcData['cn'][71083] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][71089] = {name = "烈日行者德兹科", subname = "逐晨者酋长"}
MultiLanguageNpcData['cn'][71100] = {name = "低薪工程师", subname = nil}
MultiLanguageNpcData['cn'][71105] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71108] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71109] = {name = "雪怒的挑战之锣", subname = nil}
MultiLanguageNpcData['cn'][71113] = {name = "库卡隆神射手", subname = nil}
MultiLanguageNpcData['cn'][71114] = {name = "库卡隆幻象师", subname = nil}
MultiLanguageNpcData['cn'][71116] = {name = "库卡隆战狼", subname = nil}
MultiLanguageNpcData['cn'][71126] = {name = "迅捷蓝色迅猛龙", subname = nil}
MultiLanguageNpcData['cn'][71127] = {name = "迅捷绿色迅猛龙", subname = nil}
MultiLanguageNpcData['cn'][71128] = {name = "迅捷橙色迅猛龙", subname = nil}
MultiLanguageNpcData['cn'][71132] = {name = "摇滚歌手祖鲁", subname = nil}
MultiLanguageNpcData['cn'][71139] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71142] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71144] = {name = "砮皂", subname = "玄牛"}
MultiLanguageNpcData['cn'][71146] = {name = "砮皂的挑战之锣", subname = nil}
MultiLanguageNpcData['cn'][71147] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][71148] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][71149] = {name = "萨尔", subname = nil}
MultiLanguageNpcData['cn'][71150] = {name = "陈·风暴烈酒", subname = nil}
MultiLanguageNpcData['cn'][71151] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][71165] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71166] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71169] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][71170] = {name = "赤精的挑战之锣", subname = nil}
MultiLanguageNpcData['cn'][71172] = {name = "暗矛蝙蝠骑士", subname = nil}
MultiLanguageNpcData['cn'][71173] = {name = "暗矛蝙蝠", subname = nil}
MultiLanguageNpcData['cn'][71224] = {name = "波贝的灵魂之鼓", subname = nil}
MultiLanguageNpcData['cn'][71226] = {name = "拉薇卡", subname = "暗矛起义军军需官"}
MultiLanguageNpcData['cn'][71249] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][71250] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][71263] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71269] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['cn'][71275] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71281] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71282] = {name = "森金村守望者", subname = nil}
MultiLanguageNpcData['cn'][71283] = {name = "森金村守望者", subname = nil}
MultiLanguageNpcData['cn'][71285] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71288] = {name = "库卡隆预言师", subname = nil}
MultiLanguageNpcData['cn'][71290] = {name = "暗矛蝙蝠骑士", subname = nil}
MultiLanguageNpcData['cn'][71291] = {name = "暗矛蝙蝠", subname = nil}
MultiLanguageNpcData['cn'][71305] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71306] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71307] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71308] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71317] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71319] = {name = "森金村守望者", subname = nil}
MultiLanguageNpcData['cn'][71344] = {name = "萨尔", subname = nil}
MultiLanguageNpcData['cn'][71345] = {name = "陈·风暴烈酒", subname = nil}
MultiLanguageNpcData['cn'][71352] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71373] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71374] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71375] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71377] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71387] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71404] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71424] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71426] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71429] = {name = "干净的小水花", subname = nil}
MultiLanguageNpcData['cn'][71434] = {name = "雪怒的影像", subname = nil}
MultiLanguageNpcData['cn'][71435] = {name = "玉珑的影像", subname = nil}
MultiLanguageNpcData['cn'][71439] = {name = "砮皂的影像", subname = nil}
MultiLanguageNpcData['cn'][71441] = {name = "赤精的影像", subname = nil}
MultiLanguageNpcData['cn'][71457] = {name = "荣耀岗哨旋翼机", subname = nil}
MultiLanguageNpcData['cn'][71504] = {name = "攻城匠师黑索", subname = "黑索公司"}
MultiLanguageNpcData['cn'][71514] = {name = "锣", subname = nil}
MultiLanguageNpcData['cn'][71526] = {name = "伊丽莎白·雀歌", subname = nil}
MultiLanguageNpcData['cn'][71527] = {name = "梅洛迪", subname = nil}
MultiLanguageNpcData['cn'][71589] = {name = "繁盛挖掘者", subname = nil}
MultiLanguageNpcData['cn'][71718] = {name = "繁盛挖掘者", subname = nil}
MultiLanguageNpcData['cn'][71794] = {name = "聪明的卡夫帝", subname = nil}
MultiLanguageNpcData['cn'][71865] = {name = "加尔鲁什·地狱咆哮", subname = "酋长"}
MultiLanguageNpcData['cn'][71887] = {name = "魁麟幼崽", subname = nil}
MultiLanguageNpcData['cn'][71888] = {name = "雏凤", subname = nil}
MultiLanguageNpcData['cn'][71890] = {name = "钩爪", subname = nil}
MultiLanguageNpcData['cn'][71891] = {name = "迷你螳螂巨像", subname = nil}
MultiLanguageNpcData['cn'][71892] = {name = "云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][71893] = {name = "琥珀幼蝎", subname = nil}
MultiLanguageNpcData['cn'][71894] = {name = "火爪", subname = nil}
MultiLanguageNpcData['cn'][71895] = {name = "云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][71896] = {name = "云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][71899] = {name = "震地兽", subname = nil}
MultiLanguageNpcData['cn'][71900] = {name = "蓝针", subname = nil}
MultiLanguageNpcData['cn'][71901] = {name = "毒针", subname = nil}
MultiLanguageNpcData['cn'][71902] = {name = "凶针", subname = nil}
MultiLanguageNpcData['cn'][71905] = {name = "查理", subname = nil}
MultiLanguageNpcData['cn'][71924] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71926] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][71929] = {name = "“腌菜”苏利·麦克莱利", subname = "军情七处"}
MultiLanguageNpcData['cn'][71930] = {name = "匿踪大师琪麟", subname = nil}
MultiLanguageNpcData['cn'][71931] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][71932] = {name = "贤者马里", subname = "水语者"}
MultiLanguageNpcData['cn'][71933] = {name = "布林顿4000", subname = nil}
MultiLanguageNpcData['cn'][71934] = {name = "艾恩·戈德布鲁姆博士", subname = "侏罗纪探险队"}
MultiLanguageNpcData['cn'][72316] = {name = "斥候伊戈尔·高提", subname = "雄狮之眼"}
MultiLanguageNpcData['cn'][72392] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][72394] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][72546] = {name = "库卡隆蛮兵", subname = nil}
MultiLanguageNpcData['cn'][72661] = {name = "狂热", subname = nil}
MultiLanguageNpcData['cn'][72694] = {name = "攻城匠师黑索", subname = nil}
MultiLanguageNpcData['cn'][72695] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][72723] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][72724] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][72774] = {name = "小贩卡夫帝", subname = nil}
MultiLanguageNpcData['cn'][72870] = {name = "凯诺兹", subname = nil}
MultiLanguageNpcData['cn'][72886] = {name = "延刃碎石机", subname = nil}
MultiLanguageNpcData['cn'][72887] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['cn'][72927] = {name = "科沃克", subname = nil}
MultiLanguageNpcData['cn'][72929] = {name = "瑟拉提克琥珀大师", subname = nil}
MultiLanguageNpcData['cn'][72944] = {name = "莫克", subname = "萨满祭司训练师"}
MultiLanguageNpcData['cn'][72954] = {name = "库尔提克荣誉卫士", subname = nil}
MultiLanguageNpcData['cn'][72964] = {name = "格鲁丹", subname = "黑索公司"}
MultiLanguageNpcData['cn'][72981] = {name = "阿格隆", subname = "黑索公司"}
MultiLanguageNpcData['cn'][72986] = {name = "莎娜·火星", subname = "黑索公司"}
MultiLanguageNpcData['cn'][73012] = {name = "卡拉克西散兵", subname = nil}
MultiLanguageNpcData['cn'][73030] = {name = "陈·风暴烈酒", subname = nil}
MultiLanguageNpcData['cn'][73059] = {name = "库卡隆钢铁之星", subname = nil}
MultiLanguageNpcData['cn'][73061] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][73066] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][73082] = {name = "李大师", subname = "天神比武大会主持人"}
MultiLanguageNpcData['cn'][73084] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['cn'][73091] = {name = "黑索雇佣兵", subname = "黑索公司"}
MultiLanguageNpcData['cn'][73095] = {name = "黑索工程师", subname = "黑索公司"}
MultiLanguageNpcData['cn'][73098] = {name = "库卡隆监视者", subname = nil}
MultiLanguageNpcData['cn'][73126] = {name = "雪怒", subname = nil}
MultiLanguageNpcData['cn'][73127] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][73128] = {name = "玉珑", subname = "青龙"}
MultiLanguageNpcData['cn'][73130] = {name = "砮皂", subname = "玄牛"}
MultiLanguageNpcData['cn'][73133] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['cn'][73134] = {name = "皇帝少昊", subname = nil}
MultiLanguageNpcData['cn'][73136] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][73138] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][73149] = {name = "Quest - Legendary 5.4 - Tavern Flour Bunny - JSB", subname = nil}
MultiLanguageNpcData['cn'][73151] = {name = "亡灵卫兵奈萨里安", subname = "战争坐骑军需官"}
MultiLanguageNpcData['cn'][73275] = {name = "Bottle Bunny", subname = nil}
MultiLanguageNpcData['cn'][73318] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][73319] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][73346] = {name = "调酒师童福", subname = "旅店老板"}
MultiLanguageNpcData['cn'][73436] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['cn'][73462] = {name = "加尔鲁什·地狱咆哮", subname = "酋长"}
MultiLanguageNpcData['cn'][73476] = {name = "盐齿鳄鱼", subname = nil}
MultiLanguageNpcData['cn'][73503] = {name = "赤芝，赤精的雏鸟", subname = nil}
MultiLanguageNpcData['cn'][73505] = {name = "雪福，雪怒的幼崽", subname = nil}
MultiLanguageNpcData['cn'][73506] = {name = "皂皂，砮皂的幼犊", subname = nil}
MultiLanguageNpcData['cn'][73507] = {name = "玉兰，玉珑的子嗣", subname = nil}
MultiLanguageNpcData['cn'][73560] = {name = "火焰仆从", subname = nil}
MultiLanguageNpcData['cn'][73564] = {name = "格里兹尔·轮滑", subname = nil}
MultiLanguageNpcData['cn'][73569] = {name = "茉艾拉的凿岩机", subname = nil}
MultiLanguageNpcData['cn'][73573] = {name = "灰翼蛾", subname = nil}
MultiLanguageNpcData['cn'][73592] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][73593] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][73598] = {name = "吉安娜·普罗德摩尔", subname = nil}
MultiLanguageNpcData['cn'][73603] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][73604] = {name = "贸易大王加里维克斯", subname = "锈水财阀领袖"}
MultiLanguageNpcData['cn'][73605] = {name = "洛瑟玛·塞隆", subname = "奎尔萨拉斯的摄政王"}
MultiLanguageNpcData['cn'][73606] = {name = "希尔瓦娜斯·风行者", subname = "女妖之王"}
MultiLanguageNpcData['cn'][73607] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][73626] = {name = "新手小汤米", subname = nil}
MultiLanguageNpcData['cn'][73716] = {name = "萨鲁法尔大王", subname = nil}
MultiLanguageNpcData['cn'][73811] = {name = "繁盛挖掘者", subname = nil}
MultiLanguageNpcData['cn'][73818] = {name = "延刃碎石机", subname = nil}
MultiLanguageNpcData['cn'][73828] = {name = "焰光蛾", subname = nil}
MultiLanguageNpcData['cn'][73829] = {name = "天灵蛾", subname = nil}
MultiLanguageNpcData['cn'][73837] = {name = "皮埃尔", subname = "艾米丽·科尔的小伙伴"}
MultiLanguageNpcData['cn'][73927] = {name = "大工匠梅卡托克", subname = "侏儒之王"}
MultiLanguageNpcData['cn'][73942] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][73962] = {name = "泰兰德·语风", subname = "艾露恩的高阶女祭司"}
MultiLanguageNpcData['cn'][73965] = {name = "地狱战马", subname = nil}
MultiLanguageNpcData['cn'][73966] = {name = "恐惧战马", subname = nil}
MultiLanguageNpcData['cn'][74077] = {name = "帕米", subname = nil}
MultiLanguageNpcData['cn'][74130] = {name = "加尔鲁什", subname = "地狱咆哮之子"}
MultiLanguageNpcData['cn'][74217] = {name = "大工匠梅卡托克", subname = "侏儒之王"}
MultiLanguageNpcData['cn'][91914] = {name = "拍卖行", subname = nil}
MultiLanguageNpcData['cn'][162539] = {name = "世界天赋大师", subname = "天赋大师"}
MultiLanguageNpcData['cn'][166359] = {name = "祖利安猛虎", subname = nil}
MultiLanguageNpcData['cn'][168833] = {name = "Nate Yurisist", subname = "自然抗性商人"}
MultiLanguageNpcData['cn'][168834] = {name = "Phlas Kanfrost", subname = "消耗品和特殊物品"}
MultiLanguageNpcData['cn'][169106] = {name = "Shea Dorrisist", subname = "暗影抗性商人"}
MultiLanguageNpcData['cn'][173338] = {name = "Invisible Bunny", subname = nil}
MultiLanguageNpcData['cn'][173754] = {name = "玛丁雷少校", subname = nil}
MultiLanguageNpcData['cn'][173758] = {name = "伦萨克", subname = nil}
MultiLanguageNpcData['cn'][174404] = {name = "Invisible Bunny", subname = nil}
MultiLanguageNpcData['cn'][176437] = {name = "Heigan Aggro Trigger", subname = nil}
MultiLanguageNpcData['cn'][176443] = {name = "假人", subname = nil}
MultiLanguageNpcData['cn'][176490] = {name = "预言者斯克拉姆", subname = nil}
MultiLanguageNpcData['cn'][176525] = {name = "预言者斯克拉姆", subname = nil}
MultiLanguageNpcData['cn'][176546] = {name = "Call for Help Trigger", subname = nil}
MultiLanguageNpcData['cn'][176547] = {name = "Call for Help Trigger", subname = nil}
MultiLanguageNpcData['cn'][176552] = {name = "奥格瑞玛", subname = nil}
MultiLanguageNpcData['cn'][176553] = {name = "暴风城", subname = nil}
MultiLanguageNpcData['cn'][176663] = {name = "Call for Help Trigger", subname = nil}
MultiLanguageNpcData['cn'][176708] = {name = "再度觉醒的相位捕猎者", subname = nil}
MultiLanguageNpcData['cn'][177064] = {name = "施法者假人", subname = nil}
MultiLanguageNpcData['cn'][177297] = {name = "节点领主小杜琼·莱德", subname = "测试服传送"}
MultiLanguageNpcData['cn'][177659] = {name = "首领假人", subname = nil}
MultiLanguageNpcData['cn'][178420] = {name = "魔导师阿斯塔洛·血誓", subname = nil}
MultiLanguageNpcData['cn'][178449] = {name = "普通猎人宠物", subname = nil}
MultiLanguageNpcData['cn'][178858] = {name = "占位符队长", subname = "舵手"}
MultiLanguageNpcData['cn'][181670] = {name = "抗性护甲商人", subname = nil}
MultiLanguageNpcData['cn'][181760] = {name = "竞技场布告牌", subname = nil}
MultiLanguageNpcData['cn'][184259] = {name = "夜之领主", subname = nil}
MultiLanguageNpcData['cn'][184261] = {name = "轻浮的招待", subname = nil}
MultiLanguageNpcData['cn'][184263] = {name = "狂热伙伴", subname = nil}
MultiLanguageNpcData['cn'][185317] = {name = "夜魔", subname = nil}
MultiLanguageNpcData['cn'][185334] = {name = "艾萨克·皮尔森", subname = nil}
MultiLanguageNpcData['cn'][186207] = {name = "Invisible Bunny", subname = nil}
MultiLanguageNpcData['cn'][189739] = {name = "卡鲁亚克鲸须风筝", subname = nil}
MultiLanguageNpcData['cn'][194795] = {name = "鱼语者伊尔塔斯克", subname = nil}
MultiLanguageNpcData['cn'][198525] = {name = "腐溃翡翠幼龙", subname = nil}
MultiLanguageNpcData['cn'][198706] = {name = "镜像", subname = nil}
MultiLanguageNpcData['cn'][205997] = {name = "镜像", subname = nil}
MultiLanguageNpcData['cn'][205998] = {name = "镜像", subname = nil}
MultiLanguageNpcData['cn'][205999] = {name = "镜像", subname = nil}
MultiLanguageNpcData['cn'][207128] = {name = "活化星座", subname = "赛德里尔精华交易"}
MultiLanguageNpcData['cn'][211332] = {name = "柯拉琳·裂愿", subname = "亵渎者的天灾石交易员"}
MultiLanguageNpcData['cn'][211340] = {name = "克拉莱·碎梦", subname = "亵渎者的天灾石交易员"}
MultiLanguageNpcData['cn'][234135] = {name = "蓝晶守护者", subname = "裂隙石碎片兑换商"}
MultiLanguageNpcData['cn'][234503] = {name = "染煞骑乘虎", subname = nil}
MultiLanguageNpcData['cn'][234505] = {name = "染煞云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][239945] = {name = "阿兰尼亚·空木", subname = "熔火前线招募官"}
MultiLanguageNpcData['cn'][241467] = {name = "希尔丝塔萨", subname = "龙眠联军军需官"}
MultiLanguageNpcData['cn'][244995] = {name = "浗", subname = "烟瀑之灵"}
MultiLanguageNpcData['cn'][246246] = {name = "暗影主宰塞铎", subname = "搜魂使"}
MultiLanguageNpcData['cn'][247440] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][247447] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][247730] = {name = "雪怒", subname = "白虎"}
MultiLanguageNpcData['cn'][247731] = {name = "砮皂", subname = "玄牛"}
MultiLanguageNpcData['cn'][247732] = {name = "玉珑", subname = "青龙"}
MultiLanguageNpcData['cn'][252803] = {name = "热油大锅", subname = nil}
MultiLanguageNpcData['cn'][253198] = {name = "大夜魔", subname = nil}
MultiLanguageNpcData['cn'][255994] = {name = "埃索达复制品", subname = nil}
