MultiLanguageNpcData['cn'][64977] = {name = "玛瑙云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][65149] = {name = "卡拉克西瓦·洛尔", subname = nil}
MultiLanguageNpcData['cn'][65191] = {name = "猫鼬", subname = nil}
MultiLanguageNpcData['cn'][65192] = {name = "猫鼬幼崽", subname = nil}
MultiLanguageNpcData['cn'][65204] = {name = "兴奋的萤火虫", subname = nil}
MultiLanguageNpcData['cn'][65205] = {name = "镀金飞蛾", subname = nil}
MultiLanguageNpcData['cn'][65206] = {name = "金色麝猫", subname = nil}
MultiLanguageNpcData['cn'][65207] = {name = "金色麝猫幼崽", subname = nil}
MultiLanguageNpcData['cn'][65209] = {name = "欢跃水黾", subname = nil}
MultiLanguageNpcData['cn'][65211] = {name = "黄腹牛蛙", subname = nil}
MultiLanguageNpcData['cn'][65223] = {name = "亡首蟑螂", subname = nil}
MultiLanguageNpcData['cn'][65247] = {name = "Player Clone (TEMP)", subname = nil}
MultiLanguageNpcData['cn'][65343] = {name = "白骨蜘蛛", subname = nil}
MultiLanguageNpcData['cn'][65395] = {name = "卡拉克西瓦·伊克", subname = nil}
MultiLanguageNpcData['cn'][65396] = {name = "卡拉克西瓦·库尔", subname = nil}
MultiLanguageNpcData['cn'][65397] = {name = "卡拉克西瓦·科里克", subname = nil}
MultiLanguageNpcData['cn'][65398] = {name = "卡拉克西瓦·瑟拉", subname = nil}
MultiLanguageNpcData['cn'][65434] = {name = "General Purpose Bunny ZTO", subname = nil}
MultiLanguageNpcData['cn'][65443] = {name = "炸弹目标", subname = nil}
MultiLanguageNpcData['cn'][65445] = {name = "螳螂妖", subname = nil}
MultiLanguageNpcData['cn'][65446] = {name = "地精船长", subname = nil}
MultiLanguageNpcData['cn'][65447] = {name = "地精水兵", subname = nil}
MultiLanguageNpcData['cn'][65449] = {name = "地精船员", subname = nil}
MultiLanguageNpcData['cn'][65561] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][65596] = {name = "小罐头", subname = nil}
MultiLanguageNpcData['cn'][65630] = {name = "雷电之王", subname = nil}
MultiLanguageNpcData['cn'][65648] = {name = "老马当劳", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][65651] = {name = "林塞", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][65655] = {name = "埃里克·戴维森", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][65656] = {name = "比尔·巴克勒", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][65725] = {name = "云气", subname = nil}
MultiLanguageNpcData['cn'][65758] = {name = "XE-321爆破机器人", subname = nil}
MultiLanguageNpcData['cn'][65763] = {name = "奥苏尔投树车", subname = nil}
MultiLanguageNpcData['cn'][65764] = {name = "奥苏尔入侵者", subname = nil}
MultiLanguageNpcData['cn'][65766] = {name = "老陈", subname = nil}
MultiLanguageNpcData['cn'][65767] = {name = "卡拉克西瓦·伊克", subname = nil}
MultiLanguageNpcData['cn'][65771] = {name = "林·默拳", subname = nil}
MultiLanguageNpcData['cn'][65780] = {name = "贡达", subname = nil}
MultiLanguageNpcData['cn'][65781] = {name = "孙娜·默拳", subname = nil}
MultiLanguageNpcData['cn'][65782] = {name = "班·熊心", subname = nil}
MultiLanguageNpcData['cn'][65843] = {name = "铁腕旋翼机", subname = nil}
MultiLanguageNpcData['cn'][65895] = {name = "砮皂", subname = "玄牛"}
MultiLanguageNpcData['cn'][65898] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][65902] = {name = "雪怒", subname = nil}
MultiLanguageNpcData['cn'][65904] = {name = "玉珑", subname = "青龙"}
MultiLanguageNpcData['cn'][65961] = {name = "锦绣谷大门", subname = nil}
MultiLanguageNpcData['cn'][66036] = {name = "螳螂妖飞行者", subname = nil}
MultiLanguageNpcData['cn'][66053] = {name = "莱文·晨刃", subname = nil}
MultiLanguageNpcData['cn'][66055] = {name = "奎·秋光", subname = nil}
MultiLanguageNpcData['cn'][66056] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][66057] = {name = "鲁克·石趾", subname = nil}
MultiLanguageNpcData['cn'][66058] = {name = "和谐者智先生", subname = "金莲护法"}
MultiLanguageNpcData['cn'][66059] = {name = "禾·软足", subname = nil}
MultiLanguageNpcData['cn'][66061] = {name = "安济·秋光", subname = nil}
MultiLanguageNpcData['cn'][66064] = {name = "调酒师拓莫若", subname = "旅店老板"}
MultiLanguageNpcData['cn'][66065] = {name = "涂大厨", subname = nil}
MultiLanguageNpcData['cn'][66066] = {name = "烈日行者德兹科", subname = "逐晨者酋长"}
MultiLanguageNpcData['cn'][66072] = {name = "昆莱难民 01", subname = nil}
MultiLanguageNpcData['cn'][66074] = {name = "昆莱难民 02", subname = nil}
MultiLanguageNpcData['cn'][66126] = {name = "祖塔", subname = "热情的宠物训练师"}
MultiLanguageNpcData['cn'][66135] = {name = "凶狠的达戈", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66136] = {name = "安纳林", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66212] = {name = "巨魔高阶牧师", subname = nil}
MultiLanguageNpcData['cn'][66278] = {name = "野鬼", subname = nil}
MultiLanguageNpcData['cn'][66292] = {name = "空军上将罗杰斯", subname = nil}
MultiLanguageNpcData['cn'][66300] = {name = "天火号士兵", subname = nil}
MultiLanguageNpcData['cn'][66352] = {name = "叛徒格鲁克", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66365] = {name = "翡翠触须", subname = nil}
MultiLanguageNpcData['cn'][66370] = {name = "罗杰斯上将的私人旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66398] = {name = "加尔鲁什尔步兵", subname = nil}
MultiLanguageNpcData['cn'][66412] = {name = "艾琳娜·振翼", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66422] = {name = "卡桑德拉·卡布", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66436] = {name = "杰出的高雷兹勒", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66442] = {name = "佐尔坦", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66448] = {name = "隐秘蜥蜴", subname = nil}
MultiLanguageNpcData['cn'][66452] = {name = "科拉·恐怖图腾", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66460] = {name = "天火号旋翼机飞行员", subname = nil}
MultiLanguageNpcData['cn'][66466] = {name = "“冷血”崔克斯", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66473] = {name = "天火号旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66478] = {name = "大卫·寇斯", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66512] = {name = "德扎·疫角", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66515] = {name = "科塔兹·黑锤", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66518] = {name = "伊芙瑞莎", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66520] = {name = "杜林·黑锤", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66522] = {name = "莉迪亚·埃考斯特", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66550] = {name = "尼基·微技", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66551] = {name = "拉斯安", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66552] = {name = "纳洛克", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66553] = {name = "莫勒鲁长老", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66557] = {name = "血骑士安塔里", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66561] = {name = "戈玛·阿桑", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66579] = {name = "寡妇幼蛛", subname = nil}
MultiLanguageNpcData['cn'][66580] = {name = "蜘蛛", subname = nil}
MultiLanguageNpcData['cn'][66583] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][66601] = {name = "烈焰之子", subname = nil}
MultiLanguageNpcData['cn'][66603] = {name = "利尔·夜风", subname = "军情七处"}
MultiLanguageNpcData['cn'][66635] = {name = "毕格·爆索", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66636] = {name = "差点没头的雅各布", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66638] = {name = "奥克鲁特·荒龙", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66639] = {name = "格特瑞奇", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66641] = {name = "天火号士兵", subname = nil}
MultiLanguageNpcData['cn'][66656] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66663] = {name = "螳螂妖飞行者", subname = nil}
MultiLanguageNpcData['cn'][66664] = {name = "温驯幼龙", subname = nil}
MultiLanguageNpcData['cn'][66669] = {name = "荒龙奴役者", subname = nil}
MultiLanguageNpcData['cn'][66674] = {name = "炮舰炮台", subname = nil}
MultiLanguageNpcData['cn'][66675] = {name = "派恩少校", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66697] = {name = "利尔·夜风", subname = "军情七处"}
MultiLanguageNpcData['cn'][66727] = {name = "科里克提克渗透者", subname = nil}
MultiLanguageNpcData['cn'][66730] = {name = "圣地的俞娜", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66733] = {name = "莫鲁克", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66734] = {name = "农夫倪石", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66738] = {name = "勇敢的尹勇", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66739] = {name = "废土行者苏游", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66741] = {name = "天选者亚济", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66747] = {name = "血池", subname = nil}
MultiLanguageNpcData['cn'][66796] = {name = "多伦上尉", subname = nil}
MultiLanguageNpcData['cn'][66815] = {name = "鲍丁·固拳", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66819] = {name = "布洛克", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66822] = {name = "高兹·怨怒", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][66824] = {name = "奥巴里斯", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66855] = {name = "利尔·夜风", subname = "军情七处"}
MultiLanguageNpcData['cn'][66856] = {name = "空军上将罗杰斯", subname = nil}
MultiLanguageNpcData['cn'][66865] = {name = "碧克斯·投弹", subname = nil}
MultiLanguageNpcData['cn'][66866] = {name = "瘢牙", subname = nil}
MultiLanguageNpcData['cn'][66871] = {name = "智者威利", subname = nil}
MultiLanguageNpcData['cn'][66872] = {name = "暴怒的范毅", subname = nil}
MultiLanguageNpcData['cn'][66896] = {name = "铁腕旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66897] = {name = "铁腕旋翼机", subname = nil}
MultiLanguageNpcData['cn'][66913] = {name = "Stormwind to Pandatia - Alliance intro Scene - CLIENT-SIDE - JSB", subname = nil}
MultiLanguageNpcData['cn'][66915] = {name = "库卡隆精英", subname = nil}
MultiLanguageNpcData['cn'][66918] = {name = "探索者祖什", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][66919] = {name = "“腌菜”苏利·麦克莱利", subname = "军情七处"}
MultiLanguageNpcData['cn'][66921] = {name = "米希卡", subname = "军情七处"}
MultiLanguageNpcData['cn'][66922] = {name = "安玻·吉尔妮", subname = "军情七处"}
MultiLanguageNpcData['cn'][66924] = {name = "尼姆·杰码", subname = "军情七处"}
MultiLanguageNpcData['cn'][66927] = {name = "诺德·杰码", subname = "军情七处"}
MultiLanguageNpcData['cn'][66931] = {name = "暴风城士兵", subname = nil}
MultiLanguageNpcData['cn'][66942] = {name = "徘徊煞魔", subname = nil}
MultiLanguageNpcData['cn'][66961] = {name = "纳兹戈林将军", subname = nil}
MultiLanguageNpcData['cn'][66993] = {name = "海伦娜·斯坦顿", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][67003] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][67011] = {name = "加尔鲁什尔步兵", subname = nil}
MultiLanguageNpcData['cn'][67063] = {name = "天火号轰炸机", subname = nil}
MultiLanguageNpcData['cn'][67067] = {name = "利尔的旋翼机", subname = nil}
MultiLanguageNpcData['cn'][67068] = {name = "利尔的旋翼机", subname = nil}
MultiLanguageNpcData['cn'][67158] = {name = "库卡隆精英", subname = nil}
MultiLanguageNpcData['cn'][67159] = {name = "白虎寺武僧", subname = nil}
MultiLanguageNpcData['cn'][67249] = {name = "熊猫人奴隶", subname = "熊猫人奴隶"}
MultiLanguageNpcData['cn'][67281] = {name = "上油工人", subname = nil}
MultiLanguageNpcData['cn'][67304] = {name = "神盾步兵", subname = nil}
MultiLanguageNpcData['cn'][67334] = {name = "血柄荣誉卫士", subname = "血柄荣誉卫士"}
MultiLanguageNpcData['cn'][67344] = {name = "迅捷灰狼", subname = nil}
MultiLanguageNpcData['cn'][67359] = {name = "天火号旋翼机X2型", subname = nil}
MultiLanguageNpcData['cn'][67370] = {name = "杰里米·费舍尔", subname = "驯宠大师"}
MultiLanguageNpcData['cn'][67386] = {name = "空军上将罗杰斯", subname = nil}
MultiLanguageNpcData['cn'][67387] = {name = "工匠大师欧沃斯巴克", subname = "侏儒工程学首席技师"}
MultiLanguageNpcData['cn'][67395] = {name = "滩头歼灭者", subname = nil}
MultiLanguageNpcData['cn'][67461] = {name = "血柄督军", subname = nil}
MultiLanguageNpcData['cn'][67493] = {name = "自动攻城器4000型", subname = nil}
MultiLanguageNpcData['cn'][67496] = {name = "自动干扰器9000型", subname = nil}
MultiLanguageNpcData['cn'][67560] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][67607] = {name = "终极科普罗德2500型", subname = "限量版"}
MultiLanguageNpcData['cn'][67634] = {name = "Well Supplied Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67666] = {name = "Well Fed Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67679] = {name = "锦绣阔步者", subname = nil}
MultiLanguageNpcData['cn'][67687] = {name = "特攻队指挥官", subname = nil}
MultiLanguageNpcData['cn'][67733] = {name = "Inspired Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67761] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][67765] = {name = "天火号旋翼机飞行员", subname = nil}
MultiLanguageNpcData['cn'][67768] = {name = "沼泽欢跳者", subname = nil}
MultiLanguageNpcData['cn'][67771] = {name = "珀光萤火虫", subname = nil}
MultiLanguageNpcData['cn'][67801] = {name = "大元帅双辫", subname = nil}
MultiLanguageNpcData['cn'][67808] = {name = "JINYU Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][67817] = {name = "Bubble Trap Vehicle", subname = nil}
MultiLanguageNpcData['cn'][67822] = {name = "雄狮港精兵", subname = nil}
MultiLanguageNpcData['cn'][67867] = {name = "加尔鲁什·地狱咆哮", subname = "酋长"}
MultiLanguageNpcData['cn'][67897] = {name = "侏儒飞行器", subname = nil}
MultiLanguageNpcData['cn'][67936] = {name = "GNOME Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][67938] = {name = "Well Lubricated Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67941] = {name = "油腻的蛇", subname = nil}
MultiLanguageNpcData['cn'][67959] = {name = "工匠大师欧沃斯巴克", subname = "侏儒工程学首席技师"}
MultiLanguageNpcData['cn'][67961] = {name = "GNOME Gadget Bunny", subname = nil}
MultiLanguageNpcData['cn'][67967] = {name = "神盾机械碾压者", subname = nil}
MultiLanguageNpcData['cn'][67973] = {name = "吉恩·格雷迈恩", subname = nil}
MultiLanguageNpcData['cn'][67975] = {name = "Inspired Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][67976] = {name = "工匠大师欧沃斯巴克", subname = "侏儒工程学首席技师"}
MultiLanguageNpcData['cn'][68003] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['cn'][68004] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68005] = {name = "青玉战神", subname = nil}
MultiLanguageNpcData['cn'][68018] = {name = "裘碧卡·碎影", subname = "恶魔学识大师"}
MultiLanguageNpcData['cn'][68019] = {name = "坎雷萨德·埃伯洛克", subname = "黑暗收割领袖"}
MultiLanguageNpcData['cn'][68025] = {name = "萨尔", subname = nil}
MultiLanguageNpcData['cn'][68038] = {name = "阿格娜", subname = nil}
MultiLanguageNpcData['cn'][68052] = {name = "夺日者平民", subname = nil}
MultiLanguageNpcData['cn'][68059] = {name = "萨尔", subname = nil}
MultiLanguageNpcData['cn'][68084] = {name = "洛瑟玛·塞隆", subname = "奎尔萨拉斯的摄政王"}
MultiLanguageNpcData['cn'][68098] = {name = "灰舌工人", subname = nil}
MultiLanguageNpcData['cn'][68101] = {name = "DWARF Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][68103] = {name = "Inspired Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68106] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68108] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68116] = {name = "Loaded for Bear Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68138] = {name = "火箭鸡", subname = nil}
MultiLanguageNpcData['cn'][68145] = {name = "军团萨特", subname = nil}
MultiLanguageNpcData['cn'][68147] = {name = "伊利达雷萨特", subname = nil}
MultiLanguageNpcData['cn'][68150] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68151] = {name = "秩序精华", subname = nil}
MultiLanguageNpcData['cn'][68210] = {name = "矮人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68213] = {name = "工作完成", subname = nil}
MultiLanguageNpcData['cn'][68214] = {name = "锦鱼人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68235] = {name = "吉恩·格雷迈恩", subname = nil}
MultiLanguageNpcData['cn'][68263] = {name = "熊猫人焰火", subname = nil}
MultiLanguageNpcData['cn'][68278] = {name = "洛瑟玛·塞隆", subname = "奎尔萨拉斯的摄政王"}
MultiLanguageNpcData['cn'][68287] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][68289] = {name = "克希利", subname = nil}
MultiLanguageNpcData['cn'][68303] = {name = "PANDAREN Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][68324] = {name = "Hair of the Dog Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68327] = {name = "暴躁萤火虫", subname = nil}
MultiLanguageNpcData['cn'][68330] = {name = "Cauldron Bunny", subname = nil}
MultiLanguageNpcData['cn'][68357] = {name = "单简", subname = "寇茹军领"}
MultiLanguageNpcData['cn'][68358] = {name = "织恐者阿瓦图", subname = nil}
MultiLanguageNpcData['cn'][68359] = {name = "Pandaren ASLEEP Bunny", subname = nil}
MultiLanguageNpcData['cn'][68396] = {name = "岩石", subname = nil}
MultiLanguageNpcData['cn'][68412] = {name = "Iron Fisted Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68415] = {name = "Crypt Bunny", subname = nil}
MultiLanguageNpcData['cn'][68462] = {name = "熊猫人流水之灵", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][68463] = {name = "熊猫人烈焰之灵", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][68464] = {name = "熊猫人微风之灵", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][68465] = {name = "熊猫人雷霆之灵", subname = "驯宠宗师"}
MultiLanguageNpcData['cn'][68474] = {name = "指挥官斯卡戈什", subname = nil}
MultiLanguageNpcData['cn'][68477] = {name = "库卡隆哨兵", subname = nil}
MultiLanguageNpcData['cn'][68482] = {name = "银月学者", subname = nil}
MultiLanguageNpcData['cn'][68500] = {name = "Heavy Metal Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68509] = {name = "火箭鸡", subname = nil}
MultiLanguageNpcData['cn'][68511] = {name = "旁白", subname = nil}
MultiLanguageNpcData['cn'][68513] = {name = "鹿齿土拨鼠", subname = nil}
MultiLanguageNpcData['cn'][68518] = {name = "GNOME Trap Bunny", subname = nil}
MultiLanguageNpcData['cn'][68609] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68612] = {name = "天剑哨兵", subname = nil}
MultiLanguageNpcData['cn'][68613] = {name = "无家可归的夺日者", subname = nil}
MultiLanguageNpcData['cn'][68651] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68652] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68677] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68683] = {name = "NIGHT ELF Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['cn'][68689] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68690] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][68702] = {name = "Night Elf Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68749] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68766] = {name = "反抗的夺日者", subname = nil}
MultiLanguageNpcData['cn'][68771] = {name = "重装狮鹫", subname = nil}
MultiLanguageNpcData['cn'][68773] = {name = "重装双足飞龙", subname = nil}
MultiLanguageNpcData['cn'][68776] = {name = "Inspired Buff Bunny", subname = nil}
MultiLanguageNpcData['cn'][68777] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['cn'][68795] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68812] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68817] = {name = "Finale Controller Bunny", subname = nil}
MultiLanguageNpcData['cn'][68837] = {name = "侏儒飞行器", subname = nil}
MultiLanguageNpcData['cn'][68842] = {name = "泰兰德·语风", subname = "艾露恩的高阶女祭司"}
MultiLanguageNpcData['cn'][68880] = {name = "库卡隆杀戮者", subname = nil}
MultiLanguageNpcData['cn'][68881] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][68882] = {name = "加尔鲁什·地狱咆哮", subname = "酋长"}
MultiLanguageNpcData['cn'][68894] = {name = "熊猫人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68895] = {name = "熊猫人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68896] = {name = "暗夜精灵建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68897] = {name = "暗夜精灵建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68898] = {name = "锦鱼人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68899] = {name = "侏儒建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68900] = {name = "侏儒建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68901] = {name = "矮人建筑营地", subname = nil}
MultiLanguageNpcData['cn'][68904] = {name = "夙娥", subname = "仇妃"}
MultiLanguageNpcData['cn'][68905] = {name = "露琳", subname = "寂妃"}
MultiLanguageNpcData['cn'][68918] = {name = "Divine Bell Bunny", subname = nil}
MultiLanguageNpcData['cn'][68921] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][68922] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68925] = {name = "年轻的瓦里安·乌瑞恩", subname = nil}
MultiLanguageNpcData['cn'][68927] = {name = "调酒师童福", subname = "旅店老板"}
MultiLanguageNpcData['cn'][68937] = {name = "Finale Controller Bunny", subname = nil}
MultiLanguageNpcData['cn'][68966] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68970] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][68972] = {name = "吉安娜·普罗德摩尔", subname = "肯瑞托的领袖"}
MultiLanguageNpcData['cn'][68978] = {name = "夺日者难民", subname = "夺日者难民"}
MultiLanguageNpcData['cn'][69018] = {name = "Totally Generic Bunny (JSB)", subname = nil}
MultiLanguageNpcData['cn'][69025] = {name = "指挥官斯卡戈什", subname = nil}
MultiLanguageNpcData['cn'][69026] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][69028] = {name = "Generic Client-Side Bunny", subname = nil}
MultiLanguageNpcData['cn'][69045] = {name = "加尔鲁什", subname = "地狱咆哮之子"}
MultiLanguageNpcData['cn'][69048] = {name = "希尔瓦娜斯·风行者", subname = nil}
MultiLanguageNpcData['cn'][69161] = {name = "乌达斯塔", subname = nil}
MultiLanguageNpcData['cn'][69170] = {name = "赞达拉平民", subname = nil}
MultiLanguageNpcData['cn'][69257] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][69294] = {name = "赞达拉血卫士", subname = nil}
MultiLanguageNpcData['cn'][69295] = {name = "赞达拉侍僧", subname = nil}
MultiLanguageNpcData['cn'][69296] = {name = "赞达拉屈魂者", subname = nil}
MultiLanguageNpcData['cn'][69601] = {name = "重磅炸药", subname = nil}
MultiLanguageNpcData['cn'][69651] = {name = "战神阿尔图克拉", subname = nil}
MultiLanguageNpcData['cn'][69652] = {name = "山怖", subname = nil}
MultiLanguageNpcData['cn'][69654] = {name = "雷神", subname = "雷电之王"}
MultiLanguageNpcData['cn'][69755] = {name = "战神阿尔图克拉", subname = nil}
MultiLanguageNpcData['cn'][69782] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][69888] = {name = "莱登", subname = "堕落的暴风守护者"}
MultiLanguageNpcData['cn'][69890] = {name = "蓝色小熊猫", subname = nil}
MultiLanguageNpcData['cn'][69915] = {name = "拉斯塔哈大王", subname = nil}
MultiLanguageNpcData['cn'][69918] = {name = "祖尔", subname = nil}
MultiLanguageNpcData['cn'][69945] = {name = "赞达拉荣誉守卫", subname = nil}
MultiLanguageNpcData['cn'][69950] = {name = "纳迦影像", subname = "纳迦影像"}
MultiLanguageNpcData['cn'][70052] = {name = "恶魔灵魂井", subname = nil}
MultiLanguageNpcData['cn'][70084] = {name = "泰瑞纳斯·米奈希尔", subname = nil}
MultiLanguageNpcData['cn'][70116] = {name = "魔古平民", subname = nil}
MultiLanguageNpcData['cn'][70225] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][70261] = {name = "Placeholder Creature", subname = nil}
MultiLanguageNpcData['cn'][70279] = {name = "茉艾拉·索瑞森", subname = "黑铁执政女王"}
MultiLanguageNpcData['cn'][70335] = {name = "季·火掌", subname = "火金大师"}
MultiLanguageNpcData['cn'][70438] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][70473] = {name = "霜鬃猎头者", subname = nil}
MultiLanguageNpcData['cn'][70476] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][70543] = {name = "赞达拉煽动者", subname = nil}
MultiLanguageNpcData['cn'][70626] = {name = "深渊魔", subname = nil}
MultiLanguageNpcData['cn'][70789] = {name = "赞达拉暴怒旗帜", subname = nil}
MultiLanguageNpcData['cn'][70799] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][70921] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][70968] = {name = "库卡隆好战者", subname = nil}
MultiLanguageNpcData['cn'][70971] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][70972] = {name = "森金村守望者", subname = nil}
MultiLanguageNpcData['cn'][70974] = {name = "神庙大门", subname = nil}
MultiLanguageNpcData['cn'][70978] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][70980] = {name = "先知昊梵舟", subname = nil}
MultiLanguageNpcData['cn'][70986] = {name = "库卡隆将领", subname = nil}
MultiLanguageNpcData['cn'][70989] = {name = "玉珑", subname = "青龙"}
MultiLanguageNpcData['cn'][71003] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71008] = {name = "库卡隆空降兵", subname = nil}
MultiLanguageNpcData['cn'][71029] = {name = "玉珑的挑战之锣", subname = nil}
MultiLanguageNpcData['cn'][71039] = {name = "贫瘠之地车队货车", subname = nil}
MultiLanguageNpcData['cn'][71040] = {name = "贫瘠之地车队科多兽", subname = nil}
MultiLanguageNpcData['cn'][71044] = {name = "基尔里克", subname = nil}
MultiLanguageNpcData['cn'][71063] = {name = "先知昊梵舟", subname = nil}
MultiLanguageNpcData['cn'][71065] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][71066] = {name = "库卡隆监视者", subname = nil}
MultiLanguageNpcData['cn'][71083] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][71089] = {name = "烈日行者德兹科", subname = "逐晨者酋长"}
MultiLanguageNpcData['cn'][71105] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71108] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71109] = {name = "雪怒的挑战之锣", subname = nil}
MultiLanguageNpcData['cn'][71113] = {name = "库卡隆神射手", subname = nil}
MultiLanguageNpcData['cn'][71114] = {name = "库卡隆幻象师", subname = nil}
MultiLanguageNpcData['cn'][71116] = {name = "库卡隆战狼", subname = nil}
MultiLanguageNpcData['cn'][71126] = {name = "迅捷蓝色迅猛龙", subname = nil}
MultiLanguageNpcData['cn'][71127] = {name = "迅捷绿色迅猛龙", subname = nil}
MultiLanguageNpcData['cn'][71128] = {name = "迅捷橙色迅猛龙", subname = nil}
MultiLanguageNpcData['cn'][71132] = {name = "摇滚歌手祖鲁", subname = nil}
MultiLanguageNpcData['cn'][71139] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71142] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71144] = {name = "砮皂", subname = "玄牛"}
MultiLanguageNpcData['cn'][71146] = {name = "砮皂的挑战之锣", subname = nil}
MultiLanguageNpcData['cn'][71147] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][71148] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][71149] = {name = "萨尔", subname = nil}
MultiLanguageNpcData['cn'][71150] = {name = "陈·风暴烈酒", subname = nil}
MultiLanguageNpcData['cn'][71151] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][71165] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71166] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71169] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][71170] = {name = "赤精的挑战之锣", subname = nil}
MultiLanguageNpcData['cn'][71172] = {name = "暗矛蝙蝠骑士", subname = nil}
MultiLanguageNpcData['cn'][71173] = {name = "暗矛蝙蝠", subname = nil}
MultiLanguageNpcData['cn'][71224] = {name = "波贝的灵魂之鼓", subname = nil}
MultiLanguageNpcData['cn'][71249] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][71250] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][71263] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71269] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['cn'][71275] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71281] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71282] = {name = "森金村守望者", subname = nil}
MultiLanguageNpcData['cn'][71283] = {name = "森金村守望者", subname = nil}
MultiLanguageNpcData['cn'][71285] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71288] = {name = "库卡隆预言师", subname = nil}
MultiLanguageNpcData['cn'][71290] = {name = "暗矛蝙蝠骑士", subname = nil}
MultiLanguageNpcData['cn'][71291] = {name = "暗矛蝙蝠", subname = nil}
MultiLanguageNpcData['cn'][71305] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71306] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71307] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71308] = {name = "森金村守护者", subname = nil}
MultiLanguageNpcData['cn'][71317] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71319] = {name = "森金村守望者", subname = nil}
MultiLanguageNpcData['cn'][71344] = {name = "萨尔", subname = nil}
MultiLanguageNpcData['cn'][71345] = {name = "陈·风暴烈酒", subname = nil}
MultiLanguageNpcData['cn'][71352] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71373] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71374] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71375] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71377] = {name = "暗矛俘虏", subname = nil}
MultiLanguageNpcData['cn'][71387] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71404] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71424] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71426] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71429] = {name = "干净的小水花", subname = nil}
MultiLanguageNpcData['cn'][71434] = {name = "雪怒的影像", subname = nil}
MultiLanguageNpcData['cn'][71435] = {name = "玉珑的影像", subname = nil}
MultiLanguageNpcData['cn'][71439] = {name = "砮皂的影像", subname = nil}
MultiLanguageNpcData['cn'][71441] = {name = "赤精的影像", subname = nil}
MultiLanguageNpcData['cn'][71457] = {name = "荣耀岗哨旋翼机", subname = nil}
MultiLanguageNpcData['cn'][71504] = {name = "攻城匠师黑索", subname = "黑索公司"}
MultiLanguageNpcData['cn'][71514] = {name = "锣", subname = nil}
MultiLanguageNpcData['cn'][71589] = {name = "繁盛挖掘者", subname = nil}
MultiLanguageNpcData['cn'][71718] = {name = "繁盛挖掘者", subname = nil}
MultiLanguageNpcData['cn'][71794] = {name = "聪明的卡夫帝", subname = nil}
MultiLanguageNpcData['cn'][71865] = {name = "加尔鲁什·地狱咆哮", subname = "酋长"}
MultiLanguageNpcData['cn'][71887] = {name = "魁麟幼崽", subname = nil}
MultiLanguageNpcData['cn'][71888] = {name = "雏凤", subname = nil}
MultiLanguageNpcData['cn'][71890] = {name = "钩爪", subname = nil}
MultiLanguageNpcData['cn'][71891] = {name = "迷你螳螂巨像", subname = nil}
MultiLanguageNpcData['cn'][71892] = {name = "云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][71893] = {name = "琥珀幼蝎", subname = nil}
MultiLanguageNpcData['cn'][71894] = {name = "火爪", subname = nil}
MultiLanguageNpcData['cn'][71895] = {name = "云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][71896] = {name = "云端翔龙", subname = nil}
MultiLanguageNpcData['cn'][71899] = {name = "震地兽", subname = nil}
MultiLanguageNpcData['cn'][71900] = {name = "蓝针", subname = nil}
MultiLanguageNpcData['cn'][71901] = {name = "毒针", subname = nil}
MultiLanguageNpcData['cn'][71902] = {name = "凶针", subname = nil}
MultiLanguageNpcData['cn'][71905] = {name = "查理", subname = nil}
MultiLanguageNpcData['cn'][71924] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][71931] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][72316] = {name = "斥候伊戈尔·高提", subname = "雄狮之眼"}
MultiLanguageNpcData['cn'][72392] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][72394] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][72546] = {name = "库卡隆蛮兵", subname = nil}
MultiLanguageNpcData['cn'][72661] = {name = "狂热", subname = nil}
MultiLanguageNpcData['cn'][72694] = {name = "攻城匠师黑索", subname = nil}
MultiLanguageNpcData['cn'][72695] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][72723] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][72724] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][72774] = {name = "小贩卡夫帝", subname = nil}
MultiLanguageNpcData['cn'][72870] = {name = "凯诺兹", subname = nil}
MultiLanguageNpcData['cn'][72886] = {name = "延刃碎石机", subname = nil}
MultiLanguageNpcData['cn'][72887] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['cn'][72927] = {name = "科沃克", subname = nil}
MultiLanguageNpcData['cn'][72929] = {name = "瑟拉提克琥珀大师", subname = nil}
MultiLanguageNpcData['cn'][72954] = {name = "库尔提克荣誉卫士", subname = nil}
MultiLanguageNpcData['cn'][72964] = {name = "格鲁丹", subname = "黑索公司"}
MultiLanguageNpcData['cn'][72981] = {name = "阿格隆", subname = "黑索公司"}
MultiLanguageNpcData['cn'][72986] = {name = "莎娜·火星", subname = "黑索公司"}
MultiLanguageNpcData['cn'][73012] = {name = "卡拉克西散兵", subname = nil}
MultiLanguageNpcData['cn'][73059] = {name = "库卡隆钢铁之星", subname = nil}
MultiLanguageNpcData['cn'][73061] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][73066] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][73082] = {name = "李大师", subname = "天神比武大会主持人"}
MultiLanguageNpcData['cn'][73084] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['cn'][73091] = {name = "黑索雇佣兵", subname = "黑索公司"}
MultiLanguageNpcData['cn'][73095] = {name = "黑索工程师", subname = "黑索公司"}
MultiLanguageNpcData['cn'][73098] = {name = "库卡隆监视者", subname = nil}
MultiLanguageNpcData['cn'][73126] = {name = "雪怒", subname = nil}
MultiLanguageNpcData['cn'][73127] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][73128] = {name = "玉珑", subname = "青龙"}
MultiLanguageNpcData['cn'][73130] = {name = "砮皂", subname = "玄牛"}
MultiLanguageNpcData['cn'][73133] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['cn'][73134] = {name = "皇帝少昊", subname = nil}
MultiLanguageNpcData['cn'][73136] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][73138] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][73149] = {name = "Quest - Legendary 5.4 - Tavern Flour Bunny - JSB", subname = nil}
MultiLanguageNpcData['cn'][73275] = {name = "Bottle Bunny", subname = nil}
MultiLanguageNpcData['cn'][73318] = {name = "游学者周卓", subname = nil}
MultiLanguageNpcData['cn'][73319] = {name = "拉希奥", subname = "黑王子"}
MultiLanguageNpcData['cn'][73346] = {name = "调酒师童福", subname = "旅店老板"}
MultiLanguageNpcData['cn'][73436] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['cn'][73462] = {name = "加尔鲁什·地狱咆哮", subname = "酋长"}
MultiLanguageNpcData['cn'][73503] = {name = "赤芝，赤精的雏鸟", subname = nil}
MultiLanguageNpcData['cn'][73505] = {name = "雪福，雪怒的幼崽", subname = nil}
MultiLanguageNpcData['cn'][73506] = {name = "皂皂，砮皂的幼犊", subname = nil}
MultiLanguageNpcData['cn'][73507] = {name = "玉兰，玉珑的子嗣", subname = nil}
MultiLanguageNpcData['cn'][73564] = {name = "格里兹尔·轮滑", subname = nil}
MultiLanguageNpcData['cn'][73569] = {name = "茉艾拉的凿岩机", subname = nil}
MultiLanguageNpcData['cn'][73573] = {name = "灰翼蛾", subname = nil}
MultiLanguageNpcData['cn'][73592] = {name = "瓦里安·乌瑞恩国王", subname = "暴风城国王"}
MultiLanguageNpcData['cn'][73593] = {name = "祝踏岚", subname = "影踪派掌门"}
MultiLanguageNpcData['cn'][73598] = {name = "吉安娜·普罗德摩尔", subname = nil}
MultiLanguageNpcData['cn'][73603] = {name = "贝恩·血蹄", subname = "大酋长"}
MultiLanguageNpcData['cn'][73604] = {name = "贸易大王加里维克斯", subname = "锈水财阀领袖"}
MultiLanguageNpcData['cn'][73605] = {name = "洛瑟玛·塞隆", subname = "奎尔萨拉斯的摄政王"}
MultiLanguageNpcData['cn'][73606] = {name = "希尔瓦娜斯·风行者", subname = "女妖之王"}
MultiLanguageNpcData['cn'][73607] = {name = "安度因·乌瑞恩", subname = "暴风城的王子"}
MultiLanguageNpcData['cn'][73626] = {name = "新手小汤米", subname = nil}
MultiLanguageNpcData['cn'][73716] = {name = "萨鲁法尔大王", subname = nil}
MultiLanguageNpcData['cn'][73811] = {name = "繁盛挖掘者", subname = nil}
MultiLanguageNpcData['cn'][73818] = {name = "延刃碎石机", subname = nil}
MultiLanguageNpcData['cn'][73828] = {name = "焰光蛾", subname = nil}
MultiLanguageNpcData['cn'][73829] = {name = "天灵蛾", subname = nil}
MultiLanguageNpcData['cn'][73837] = {name = "皮埃尔", subname = "艾米丽·科尔的小伙伴"}
MultiLanguageNpcData['cn'][73927] = {name = "大工匠梅卡托克", subname = "侏儒之王"}
MultiLanguageNpcData['cn'][73942] = {name = "沃金", subname = nil}
MultiLanguageNpcData['cn'][73962] = {name = "泰兰德·语风", subname = "艾露恩的高阶女祭司"}
MultiLanguageNpcData['cn'][73965] = {name = "地狱战马", subname = nil}
MultiLanguageNpcData['cn'][73966] = {name = "恐惧战马", subname = nil}
MultiLanguageNpcData['cn'][74077] = {name = "帕米", subname = nil}
MultiLanguageNpcData['cn'][74130] = {name = "加尔鲁什", subname = "地狱咆哮之子"}
MultiLanguageNpcData['cn'][74217] = {name = "大工匠梅卡托克", subname = "侏儒之王"}
MultiLanguageNpcData['cn'][91914] = {name = "拍卖行", subname = nil}
MultiLanguageNpcData['cn'][162539] = {name = "世界天赋大师", subname = "天赋大师"}
MultiLanguageNpcData['cn'][166359] = {name = "祖利安猛虎", subname = nil}
MultiLanguageNpcData['cn'][168833] = {name = "Nate Yurisist", subname = "自然抗性商人"}
MultiLanguageNpcData['cn'][168834] = {name = "Phlas Kanfrost", subname = "消耗品和特殊物品"}
MultiLanguageNpcData['cn'][169106] = {name = "Shea Dorrisist", subname = "暗影抗性商人"}
MultiLanguageNpcData['cn'][173338] = {name = "Invisible Bunny", subname = nil}
MultiLanguageNpcData['cn'][173754] = {name = "玛丁雷少校", subname = nil}
MultiLanguageNpcData['cn'][173758] = {name = "Overlord Runthak", subname = nil}
MultiLanguageNpcData['cn'][174404] = {name = "Invisible Bunny", subname = nil}
MultiLanguageNpcData['cn'][176437] = {name = "Heigan Aggro Trigger", subname = nil}
MultiLanguageNpcData['cn'][176443] = {name = "假人", subname = nil}
MultiLanguageNpcData['cn'][176490] = {name = "预言者斯克拉姆", subname = nil}
MultiLanguageNpcData['cn'][176525] = {name = "预言者斯克拉姆", subname = nil}
MultiLanguageNpcData['cn'][176546] = {name = "Call for Help Trigger", subname = nil}
MultiLanguageNpcData['cn'][176547] = {name = "Call for Help Trigger", subname = nil}
MultiLanguageNpcData['cn'][176552] = {name = "奥格瑞玛", subname = nil}
MultiLanguageNpcData['cn'][176553] = {name = "暴风城", subname = nil}
MultiLanguageNpcData['cn'][176663] = {name = "Call for Help Trigger", subname = nil}
MultiLanguageNpcData['cn'][176708] = {name = "再度觉醒的相位捕猎者", subname = nil}
MultiLanguageNpcData['cn'][177064] = {name = "施法者假人", subname = nil}
MultiLanguageNpcData['cn'][177297] = {name = "节点领主小杜琼·莱德", subname = "测试服传送"}
MultiLanguageNpcData['cn'][177659] = {name = "首领假人", subname = nil}
MultiLanguageNpcData['cn'][178420] = {name = "魔导师阿斯塔洛·血誓", subname = nil}
MultiLanguageNpcData['cn'][178449] = {name = "普通猎人宠物", subname = nil}
MultiLanguageNpcData['cn'][178858] = {name = "占位符队长", subname = "舵手"}
MultiLanguageNpcData['cn'][181670] = {name = "抗性护甲商人", subname = nil}
MultiLanguageNpcData['cn'][181760] = {name = "竞技场布告牌", subname = nil}
MultiLanguageNpcData['cn'][184259] = {name = "夜之领主", subname = nil}
MultiLanguageNpcData['cn'][185317] = {name = "夜魔", subname = nil}
MultiLanguageNpcData['cn'][185334] = {name = "艾萨克·皮尔森", subname = nil}
MultiLanguageNpcData['cn'][186207] = {name = "Invisible Bunny", subname = nil}
MultiLanguageNpcData['cn'][189739] = {name = "卡鲁亚克鲸须风筝", subname = nil}
MultiLanguageNpcData['cn'][194795] = {name = "鱼语者伊尔塔斯克", subname = nil}
MultiLanguageNpcData['cn'][198525] = {name = "腐溃翡翠幼龙", subname = nil}
MultiLanguageNpcData['cn'][198706] = {name = "镜像", subname = nil}
MultiLanguageNpcData['cn'][205997] = {name = "镜像", subname = nil}
MultiLanguageNpcData['cn'][205998] = {name = "镜像", subname = nil}
MultiLanguageNpcData['cn'][205999] = {name = "镜像", subname = nil}
MultiLanguageNpcData['cn'][207128] = {name = "活化星座", subname = "赛德里尔精华交易"}
MultiLanguageNpcData['cn'][211332] = {name = "柯拉琳·裂愿", subname = "亵渎者的天灾石交易员"}
MultiLanguageNpcData['cn'][211340] = {name = "克拉莱·碎梦", subname = "亵渎者的天灾石交易员"}
MultiLanguageNpcData['cn'][247440] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][247447] = {name = "赤精", subname = "朱鹤"}
MultiLanguageNpcData['cn'][247730] = {name = "雪怒", subname = "白虎"}
MultiLanguageNpcData['cn'][247731] = {name = "砮皂", subname = "玄牛"}
MultiLanguageNpcData['cn'][247732] = {name = "玉珑", subname = "青龙"}
